// BíbliaLearn — conteúdo das unidades e lições
// Estrutura espelhada na tela de referência: 5 grandes lições na trilha.
// Vocabulário: pares EN/PT. Sentences: frases para montar com banco de palavras.
// Verses: versículos (KJV, domínio público) para exercício de lacuna.

const COURSE = [
  {
    id: "u1",
    title: "A Palavra de Deus",
    subtitle: "Gênesis 1–3",
    icon: "📖",
    face: "book",
    color: "#58a700",
    lessons: [
      {
        id: "u1l1",
        dialogue: {"line": "Look! God created the light.", "pt": "Olha! Deus criou a luz.", "options": ["It is good!", "It is night.", "Where is the ark?"], "answer": "It is good!", "answerPt": "É bom!"},
        quiz: {"q": "In the beginning, who created the heaven and the earth?", "options": ["God", "Noah", "The king"], "answer": "God", "explain": "Gênesis 1:1: no princípio, Deus criou o céu e a terra."},
        title: "Céu e terra",
        vocab: [
          { en: "God", pt: "Deus", icon: "🙏" },
          { en: "heaven", pt: "céu", icon: "🌤️" },
          { en: "earth", pt: "terra", icon: "🌍" },
          { en: "light", pt: "luz", icon: "💡" },
        ],
        sentences: [
          { en: "God created the heaven and the earth", pt: "Deus criou o céu e a terra" },
        ],
        verse: {
          text: "In the beginning God created the heaven and the earth.",
          pt: "No princípio, Deus criou o céu e a terra.",
          ref: "Gênesis 1:1",
          blank: "created",
          options: ["created", "loved", "said", "saw"],
        },
      },
      {
        id: "u1l2",
        dialogue: {"line": "Good night, my friend.", "pt": "Boa noite, meu amigo.", "options": ["Good night! The darkness is here.", "Good morning! The sun is hot.", "Let my people go."], "answer": "Good night! The darkness is here.", "answerPt": "Boa noite! As trevas chegaram."},
        quiz: {"q": "What did God call the light?", "options": ["Day", "Night", "Sea"], "answer": "Day", "explain": "Deus chamou a luz de Dia e as trevas de Noite."},
        title: "Luz e trevas",
        vocab: [
          { en: "darkness", pt: "trevas", icon: "🌑" },
          { en: "day", pt: "dia", icon: "☀️" },
          { en: "night", pt: "noite", icon: "🌙" },
          { en: "good", pt: "bom", icon: "👍" },
        ],
        sentences: [
          { en: "God called the light Day", pt: "Deus chamou a luz de Dia" },
          { en: "the darkness he called Night", pt: "às trevas ele chamou Noite" },
        ],
        verse: {
          text: "And God said, Let there be light: and there was light.",
          pt: "E disse Deus: Haja luz. E houve luz.",
          ref: "Gênesis 1:3",
          blank: "light",
          options: ["light", "water", "earth", "night"],
        },
      },
      {
        id: "u1l3",
        dialogue: {"line": "Come and see the garden!", "pt": "Vem ver o jardim!", "options": ["The tree of life is beautiful.", "The sea is dry.", "I have five stones."], "answer": "The tree of life is beautiful.", "answerPt": "A árvore da vida é linda."},
        quiz: {"q": "Where did God plant a garden?", "options": ["In Eden", "In Egypt", "In the sea"], "answer": "In Eden", "explain": "Deus plantou um jardim no Éden (Gênesis 2:8)."},
        title: "O jardim",
        vocab: [
          { en: "garden", pt: "jardim", icon: "🌳" },
          { en: "tree", pt: "árvore", icon: "🌲" },
          { en: "life", pt: "vida", icon: "🌱" },
          { en: "man", pt: "homem", icon: "🧔" },
        ],
        sentences: [
          { en: "the tree of life", pt: "a árvore da vida" },
          { en: "God saw that it was good", pt: "Deus viu que era bom" },
        ],
        verse: {
          text: "And the LORD God planted a garden eastward in Eden.",
          pt: "E plantou o Senhor Deus um jardim no Éden, do lado oriental.",
          ref: "Gênesis 2:8",
          blank: "garden",
          options: ["garden", "house", "city", "sea"],
        },
      },
      { id: "u1r", title: "Revisão", review: true },
    ],
  },
  {
    id: "u2",
    title: "Noé e a Arca",
    subtitle: "Gênesis 6–9",
    icon: "🚢",
    face: "noe",
    color: "#7e57c2",
    lessons: [
      {
        id: "u2l1",
        dialogue: {"line": "Noah, what are you making?", "pt": "Noé, o que você está fazendo?", "options": ["An ark of wood.", "A song.", "A crown."], "answer": "An ark of wood.", "answerPt": "Uma arca de madeira."},
        quiz: {"q": "What did Noah make?", "options": ["An ark of wood", "A house of stone", "A garden"], "answer": "An ark of wood", "explain": "Noé fez uma arca de madeira de gofer."},
        title: "A arca",
        vocab: [
          { en: "ark", pt: "arca", icon: "🚢" },
          { en: "rain", pt: "chuva", icon: "🌧️" },
          { en: "animals", pt: "animais", icon: "🐘" },
          { en: "door", pt: "porta", icon: "🚪" },
        ],
        sentences: [
          { en: "Noah made an ark of wood", pt: "Noé fez uma arca de madeira" },
        ],
        verse: {
          text: "Make thee an ark of gopher wood.",
          pt: "Faze para ti uma arca de madeira de gofer.",
          ref: "Gênesis 6:14",
          blank: "ark",
          options: ["ark", "boat", "tent", "wall"],
        },
      },
      {
        id: "u2l2",
        dialogue: {"line": "It is raining a lot!", "pt": "Está chovendo muito!", "options": ["Let us go into the ark.", "Let us go to the desert.", "The battle is the Lord's."], "answer": "Let us go into the ark.", "answerPt": "Vamos entrar na arca."},
        quiz: {"q": "How many days did it rain?", "options": ["Forty days", "Seven days", "Three days"], "answer": "Forty days", "explain": "Choveu quarenta dias e quarenta noites."},
        title: "O dilúvio",
        vocab: [
          { en: "flood", pt: "dilúvio", icon: "⛈️" },
          { en: "forty", pt: "quarenta", icon: "🔢" },
          { en: "water", pt: "água", icon: "💧" },
          { en: "window", pt: "janela", icon: "🪟" },
        ],
        sentences: [
          { en: "the rain was upon the earth", pt: "a chuva caiu sobre a terra" },
          { en: "forty days and forty nights", pt: "quarenta dias e quarenta noites" },
        ],
        verse: {
          text: "And the rain was upon the earth forty days and forty nights.",
          pt: "E houve chuva sobre a terra quarenta dias e quarenta noites.",
          ref: "Gênesis 7:12",
          blank: "rain",
          options: ["rain", "sun", "wind", "fire"],
        },
      },
      {
        id: "u2l3",
        dialogue: {"line": "Look at the cloud!", "pt": "Olha a nuvem!", "options": ["I see a rainbow!", "I see a giant!", "I see a harp!"], "answer": "I see a rainbow!", "answerPt": "Eu vejo um arco-íris!"},
        quiz: {"q": "What did God set in the cloud?", "options": ["A rainbow", "A dove", "A star"], "answer": "A rainbow", "explain": "Deus pôs o arco-íris na nuvem como sinal da promessa."},
        title: "A promessa",
        vocab: [
          { en: "dove", pt: "pomba", icon: "🕊️" },
          { en: "rainbow", pt: "arco-íris", icon: "🌈" },
          { en: "promise", pt: "promessa", icon: "✍️" },
          { en: "cloud", pt: "nuvem", icon: "☁️" },
        ],
        sentences: [
          { en: "the dove came back to him", pt: "a pomba voltou para ele" },
        ],
        verse: {
          text: "I do set my bow in the cloud.",
          pt: "O meu arco tenho posto na nuvem.",
          ref: "Gênesis 9:13",
          blank: "cloud",
          options: ["cloud", "sea", "field", "night"],
        },
      },
      { id: "u2r", title: "Revisão", review: true },
    ],
  },
  {
    id: "u3",
    title: "Moisés e o Êxodo",
    subtitle: "Êxodo 1–15",
    icon: "🔥",
    face: "moises",
    color: "#e6a817",
    lessons: [
      {
        id: "u3l1",
        dialogue: {"line": "Moses, take off your shoes.", "pt": "Moisés, tira as sandálias.", "options": ["Yes, this is holy ground.", "No, the sea is dry.", "Here is my harp."], "answer": "Yes, this is holy ground.", "answerPt": "Sim, este é chão santo."},
        quiz: {"q": "What did Moses see in the desert?", "options": ["A burning bush", "A big river", "A golden calf"], "answer": "A burning bush", "explain": "Moisés viu a sarça que ardia sem se consumir."},
        title: "A sarça ardente",
        vocab: [
          { en: "fire", pt: "fogo", icon: "🔥" },
          { en: "holy", pt: "santo", icon: "✨" },
          { en: "ground", pt: "chão", icon: "🟫" },
          { en: "to see", pt: "ver", icon: "👀" },
        ],
        sentences: [
          { en: "the bush burned with fire", pt: "a sarça ardia no fogo" },
        ],
        verse: {
          text: "The place whereon thou standest is holy ground.",
          pt: "O lugar em que tu estás é terra santa.",
          ref: "Êxodo 3:5",
          blank: "holy",
          options: ["holy", "dry", "cold", "far"],
        },
      },
      {
        id: "u3l2",
        dialogue: {"line": "Who are you?", "pt": "Quem é você?", "options": ["I am Moses. Let my people go.", "I am the ark.", "I am a rainbow."], "answer": "I am Moses. Let my people go.", "answerPt": "Eu sou Moisés. Deixa ir o meu povo."},
        quiz: {"q": "What did Moses say to the king?", "options": ["Let my people go", "Give me gold", "Build a city"], "answer": "Let my people go", "explain": "\"Deixa ir o meu povo\" (Êxodo 5:1)."},
        title: "Deixa o meu povo ir",
        vocab: [
          { en: "people", pt: "povo", icon: "👥" },
          { en: "free", pt: "livre", icon: "🔓" },
          { en: "king", pt: "rei", icon: "👑" },
          { en: "to go", pt: "ir", icon: "🚶" },
        ],
        sentences: [
          { en: "let my people go", pt: "deixa ir o meu povo" },
        ],
        verse: {
          text: "Thus saith the LORD God of Israel, Let my people go.",
          pt: "Assim diz o Senhor, Deus de Israel: Deixa ir o meu povo.",
          ref: "Êxodo 5:1",
          blank: "people",
          options: ["people", "sheep", "sons", "kings"],
        },
      },
      {
        id: "u3l3",
        dialogue: {"line": "Moses, the sea is in front of us!", "pt": "Moisés, o mar está na nossa frente!", "options": ["Stretch out your hand!", "Sing a song!", "Build an ark!"], "answer": "Stretch out your hand!", "answerPt": "Estende a tua mão!"},
        quiz: {"q": "What happened to the sea?", "options": ["The waters were divided", "The sea became fire", "The sea was silent"], "answer": "The waters were divided", "explain": "As águas foram divididas e o povo passou em terra seca."},
        title: "O mar se abre",
        vocab: [
          { en: "sea", pt: "mar", icon: "🌊" },
          { en: "dry", pt: "seco", icon: "🏜️" },
          { en: "hand", pt: "mão", icon: "✋" },
          { en: "wind", pt: "vento", icon: "💨" },
        ],
        sentences: [
          { en: "the waters were divided", pt: "as águas foram divididas" },
          { en: "Moses stretched out his hand", pt: "Moisés estendeu a sua mão" },
        ],
        verse: {
          text: "And the LORD made the sea dry land, and the waters were divided.",
          pt: "E o Senhor fez o mar terra seca, e as águas foram partidas.",
          ref: "Êxodo 14:21",
          blank: "sea",
          options: ["sea", "sky", "hill", "city"],
        },
      },
      { id: "u3r", title: "Revisão", review: true },
    ],
  },
  {
    id: "u4",
    title: "Davi, um coração segundo o coração de Deus",
    subtitle: "1 Samuel 16–31",
    icon: "👑",
    face: "davi",
    color: "#6a4fb3",
    lessons: [
      {
        id: "u4l1",
        dialogue: {"line": "David, where are the sheep?", "pt": "Davi, onde estão as ovelhas?", "options": ["They are in the field.", "They are in the ark.", "They are in the cloud."], "answer": "They are in the field.", "answerPt": "Elas estão no campo."},
        quiz: {"q": "Where does the Lord look?", "options": ["On the heart", "On the face", "On the hands"], "answer": "On the heart", "explain": "O Senhor olha para o coração (1 Samuel 16:7)."},
        title: "O pastorzinho",
        vocab: [
          { en: "shepherd", pt: "pastor", icon: "🧑‍🌾" },
          { en: "sheep", pt: "ovelha", icon: "🐑" },
          { en: "harp", pt: "harpa", icon: "🎶" },
          { en: "heart", pt: "coração", icon: "❤️" },
        ],
        sentences: [
          { en: "David kept the sheep", pt: "Davi cuidava das ovelhas" },
        ],
        verse: {
          text: "Man looketh on the outward appearance, but the LORD looketh on the heart.",
          pt: "O homem vê o exterior, porém o Senhor olha para o coração.",
          ref: "1 Samuel 16:7",
          blank: "heart",
          options: ["heart", "face", "hands", "house"],
        },
      },
      {
        id: "u4l2",
        dialogue: {"line": "The giant is coming!", "pt": "O gigante está vindo!", "options": ["The battle is the Lord's!", "Good night!", "I see a rainbow!"], "answer": "The battle is the Lord's!", "answerPt": "A batalha é do Senhor!"},
        quiz: {"q": "What did David take to the battle?", "options": ["Five stones", "A sword", "A crown"], "answer": "Five stones", "explain": "Davi escolheu cinco pedras lisas do ribeiro."},
        title: "Davi e Golias",
        vocab: [
          { en: "stone", pt: "pedra", icon: "🪨" },
          { en: "giant", pt: "gigante", icon: "🗿" },
          { en: "sling", pt: "funda", icon: "🎯" },
          { en: "battle", pt: "batalha", icon: "⚔️" },
        ],
        sentences: [
          { en: "the battle is the Lord's", pt: "a batalha é do Senhor" },
          { en: "David took five stones", pt: "Davi tomou cinco pedras" },
        ],
        verse: {
          text: "For the battle is the LORD's, and he will give you into our hands.",
          pt: "Porque a batalha é do Senhor, e ele vos entregará na nossa mão.",
          ref: "1 Samuel 17:47",
          blank: "battle",
          options: ["battle", "silver", "harvest", "story"],
        },
      },
      {
        id: "u4l3",
        dialogue: {"line": "David, sing for us!", "pt": "Davi, cante para nós!", "options": ["The Lord is my rock!", "The sea is dry!", "Take off your shoes!"], "answer": "The Lord is my rock!", "answerPt": "O Senhor é a minha rocha!"},
        quiz: {"q": "Who is my rock, said David?", "options": ["The Lord", "The king", "The giant"], "answer": "The Lord", "explain": "\"O Senhor é o meu rochedo\" (2 Samuel 22:2)."},
        title: "O rei cantor",
        vocab: [
          { en: "song", pt: "cântico", icon: "🎵" },
          { en: "to sing", pt: "cantar", icon: "🎤" },
          { en: "rock", pt: "rocha", icon: "⛰️" },
          { en: "strong", pt: "forte", icon: "💪" },
        ],
        sentences: [
          { en: "David sang unto the Lord", pt: "Davi cantou ao Senhor" },
        ],
        verse: {
          text: "The LORD is my rock, and my fortress, and my deliverer.",
          pt: "O Senhor é o meu rochedo, e o meu lugar forte, e o meu libertador.",
          ref: "2 Samuel 22:2",
          blank: "rock",
          options: ["rock", "song", "lamp", "road"],
        },
      },
      { id: "u4r", title: "Revisão", review: true },
    ],
  },
  {
    id: "u5",
    title: "Os Profetas",
    subtitle: "Isaías 1–12",
    icon: "📜",
    face: "isaias",
    color: "#8a8a6d",
    lessons: [
      {
        id: "u5l1",
        dialogue: {"line": "Whom shall I send?", "pt": "A quem enviarei?", "options": ["Here am I; send me.", "Send the sheep.", "Let there be light."], "answer": "Here am I; send me.", "answerPt": "Eis-me aqui, envia-me a mim."},
        quiz: {"q": "What did Isaiah answer to God?", "options": ["Here am I; send me", "I cannot go", "Send my brother"], "answer": "Here am I; send me", "explain": "\"Eis-me aqui, envia-me a mim\" (Isaías 6:8)."},
        title: "Eis-me aqui",
        vocab: [
          { en: "prophet", pt: "profeta", icon: "📜" },
          { en: "voice", pt: "voz", icon: "🗣️" },
          { en: "to send", pt: "enviar", icon: "📨" },
          { en: "to hear", pt: "ouvir", icon: "👂" },
        ],
        sentences: [
          { en: "here am I; send me", pt: "eis-me aqui, envia-me a mim" },
        ],
        verse: {
          text: "Whom shall I send, and who will go for us? Then said I, Here am I; send me.",
          pt: "A quem enviarei, e quem há de ir por nós? Então, disse eu: Eis-me aqui, envia-me a mim.",
          ref: "Isaías 6:8",
          blank: "send",
          options: ["send", "keep", "teach", "feed"],
        },
      },
      {
        id: "u5l2",
        dialogue: {"line": "What is the name of the child?", "pt": "Qual é o nome do menino?", "options": ["Immanuel: God with us.", "Goliath the giant.", "Noah of the ark."], "answer": "Immanuel: God with us.", "answerPt": "Emanuel: Deus conosco."},
        quiz: {"q": "What does Immanuel mean?", "options": ["God with us", "God is far", "King of Egypt"], "answer": "God with us", "explain": "Emanuel significa \"Deus conosco\"."},
        title: "Emanuel",
        vocab: [
          { en: "sign", pt: "sinal", icon: "⭐" },
          { en: "child", pt: "menino", icon: "👶" },
          { en: "name", pt: "nome", icon: "🏷️" },
          { en: "with us", pt: "conosco", icon: "👫" },
        ],
        sentences: [
          { en: "God with us", pt: "Deus conosco" },
        ],
        verse: {
          text: "Behold, a virgin shall conceive, and bear a son, and shall call his name Immanuel.",
          pt: "Eis que uma virgem conceberá, e dará à luz um filho, e será o seu nome Emanuel.",
          ref: "Isaías 7:14",
          blank: "name",
          options: ["name", "land", "word", "sign"],
        },
      },
      {
        id: "u5l3",
        dialogue: {"line": "Who is coming?", "pt": "Quem está vindo?", "options": ["The Prince of Peace!", "The king of Egypt!", "A big river!"], "answer": "The Prince of Peace!", "answerPt": "O Príncipe da Paz!"},
        quiz: {"q": "Who is called the Prince of Peace?", "options": ["The Son", "The king of Egypt", "The prophet"], "answer": "The Son", "explain": "Isaías 9:6 anuncia o Filho, o Príncipe da Paz."},
        title: "O Príncipe da Paz",
        vocab: [
          { en: "peace", pt: "paz", icon: "☮️" },
          { en: "prince", pt: "príncipe", icon: "🤴" },
          { en: "wonderful", pt: "maravilhoso", icon: "🌟" },
          { en: "counsellor", pt: "conselheiro", icon: "🧠" },
        ],
        sentences: [
          { en: "the Prince of Peace", pt: "o Príncipe da Paz" },
        ],
        verse: {
          text: "And his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace.",
          pt: "E o seu nome será Maravilhoso Conselheiro, Deus Forte, Pai da Eternidade, Príncipe da Paz.",
          ref: "Isaías 9:6",
          blank: "Peace",
          options: ["Peace", "Rain", "Gold", "Light"],
        },
      },
      { id: "u5r", title: "Revisão", review: true },
    ],
  },
];
