// BíbliaLearn — Cenas do dia a dia com contexto bíblico
// Cada cena é uma situação cotidiana (apresentar-se, comprar, pedir ajuda, falar do tempo...)
// vivida por um personagem num episódio real da Bíblia. O aprendiz fala pelo protagonista (char).
// Campos: id, char (protagonista), unit (capítulo da trilha), title, func (função do cotidiano),
// ref (âncora bíblica), context (PT), vocab (5 itens funcionais), lines (falas EN/PT, who = quem fala),
// truth (o que aconteceu de verdade, com referência). Inglês A1/A2, frases curtas.

// Personagens secundários que não estão na galeria (rosto em emoji, voz própria)
const SCENE_EXTRAS = {
  merchant: { name: "Mercador", gender: "male", emoji: "🧔", voice: "roger" },
  voice: { name: "A voz do Senhor", gender: "male", emoji: "✨", voice: "clyde" },
  pharaoh: { name: "Faraó", gender: "male", emoji: "👑", voice: "adam" },
  goliath: { name: "Golias", gender: "male", emoji: "🛡️", voice: "clyde" },
  jonatas: { name: "Jônatas", gender: "male", emoji: "🏹", voice: "sam" },
  saul: { name: "Rei Saul", gender: "male", emoji: "👑", voice: "james" },
  mefibosete: { name: "Mefibosete", gender: "male", emoji: "🧑", voice: "ethan" },
  jesse: { name: "Jessé", gender: "male", emoji: "👴", voice: "thomas" },
  acaz: { name: "Rei Acaz", gender: "male", emoji: "👑", voice: "harry" },
  ezequias: { name: "Rei Ezequias", gender: "male", emoji: "👑", voice: "matthew" },
  potifar: { name: "Potifar", gender: "male", emoji: "🧔‍♂️", voice: "michael" },
  copeiro: { name: "Copeiro do rei", gender: "male", emoji: "🍷", voice: "dave" },
  juda: { name: "Judá", gender: "male", emoji: "🧑‍🦱", voice: "paul" },
  ismaelita: { name: "Mercador ismaelita", gender: "male", emoji: "🐪", voice: "patrick" },
  aspenaz: { name: "Aspenaz", gender: "male", emoji: "📜", voice: "joseph" },
  nabucodonosor: { name: "Rei Nabucodonosor", gender: "male", emoji: "👑", voice: "arnold" },
  belsazar: { name: "Rei Belsazar", gender: "male", emoji: "🍷", voice: "drew" },
  dario: { name: "Rei Dario", gender: "male", emoji: "👑", voice: "patrick" },
  andre: { name: "André", gender: "male", emoji: "🎣", voice: "callum" },
  serva: { name: "Serva", gender: "female", emoji: "👩", voice: "laura" },
  coxo: { name: "Homem coxo", gender: "male", emoji: "🙏", voice: "eric" },
  povo: { name: "O povo", gender: "male", emoji: "👥", voice: "brian" },
  anjo: { name: "Anjo", gender: "male", emoji: "😇", voice: "chris" },
  sem: { name: "Sem (filho de Noé)", gender: "male", emoji: "🧑‍🌾", voice: "callum" },
  esposa: { name: "Esposa de Noé", gender: "female", emoji: "👩‍🦳", voice: "grace" },
};

const SCENES = [
  // ===================== JESUS (capítulo 1) =====================
  {
    id: "c-jesus-1", char: "jesus", unit: "u1", title: "Vem, segue-me", func: "Convidar alguém e responder ao convite",
    ref: "Mateus 4:18-22", with: "pedro",
    context: "Pedro e André lançam a rede no mar da Galileia. Jesus passa e faz um convite.",
    vocab: [
      { en: "Good morning", pt: "Bom dia", icon: "🌅" }, { en: "to fish", pt: "pescar", icon: "🎣" },
      { en: "Come with me", pt: "Venha comigo", icon: "🚶" }, { en: "right now", pt: "agora mesmo", icon: "⏱️" },
      { en: "Let's go", pt: "Vamos", icon: "➡️" },
    ],
    lines: [
      { who: "jesus", en: "Good morning! What are you doing?", pt: "Bom dia! O que vocês estão fazendo?" },
      { who: "pedro", en: "Good morning. We are fishing.", pt: "Bom dia. Estamos pescando." },
      { who: "jesus", en: "Is the fishing good today?", pt: "A pesca está boa hoje?" },
      { who: "pedro", en: "Not today. The net is empty.", pt: "Hoje não. A rede está vazia." },
      { who: "jesus", en: "Come with me. I will make you fishers of men.", pt: "Venham comigo. Eu farei de vocês pescadores de homens." },
      { who: "pedro", en: "Fishers of men? When?", pt: "Pescadores de homens? Quando?" },
      { who: "jesus", en: "Right now. Leave the net and follow me.", pt: "Agora mesmo. Deixem a rede e sigam-me." },
      { who: "pedro", en: "Yes, Lord. Let's go!", pt: "Sim, Senhor. Vamos!" },
    ],
    truth: "Jesus viu Pedro e André lançando a rede, disse \"Vinde após mim, e eu vos farei pescadores de homens\", e eles deixaram as redes imediatamente e o seguiram (Mateus 4:18-20).",
  },
  {
    id: "c-jesus-2", char: "jesus", unit: "u1", title: "Cinco pães e dois peixes", func: "Falar de comida e quantidades",
    ref: "João 6:5-13", with: "andre",
    context: "Uma multidão está com fome no monte. Jesus pergunta aos discípulos o que há para comer.",
    vocab: [
      { en: "hungry", pt: "com fome", icon: "😋" }, { en: "How many?", pt: "Quantos?", icon: "🔢" },
      { en: "bread", pt: "pão", icon: "🍞" }, { en: "fish", pt: "peixe", icon: "🐟" }, { en: "enough", pt: "suficiente", icon: "👌" },
    ],
    lines: [
      { who: "jesus", en: "The people are hungry. What do we have to eat?", pt: "O povo está com fome. O que temos para comer?" },
      { who: "andre", en: "There is a boy here with some food.", pt: "Há um menino aqui com um pouco de comida." },
      { who: "jesus", en: "How many loaves does he have?", pt: "Quantos pães ele tem?" },
      { who: "andre", en: "Five loaves and two small fish.", pt: "Cinco pães e dois peixinhos." },
      { who: "jesus", en: "That is enough. Tell the people to sit down.", pt: "É suficiente. Digam ao povo para se sentar." },
      { who: "andre", en: "Sit down? But there are five thousand people!", pt: "Sentar? Mas são cinco mil pessoas!" },
      { who: "jesus", en: "Bring me the bread and the fish, please.", pt: "Traga-me o pão e o peixe, por favor." },
      { who: "andre", en: "Here they are, Lord.", pt: "Aqui estão, Senhor." },
      { who: "jesus", en: "Thank you, Father, for this food.", pt: "Obrigado, Pai, por esta comida." },
    ],
    truth: "André achou um menino com cinco pães de cevada e dois peixinhos; Jesus deu graças, todos comeram e sobraram doze cestos (João 6:8-13).",
  },
  {
    id: "c-jesus-3", char: "jesus", unit: "u1", title: "Hoje eu fico na sua casa", func: "Receber e fazer uma visita",
    ref: "Lucas 19:1-10", with: "zaqueu",
    context: "Zaqueu, baixinho, sobe numa figueira para ver Jesus passar em Jericó.",
    vocab: [
      { en: "house", pt: "casa", icon: "🏠" }, { en: "today", pt: "hoje", icon: "📅" },
      { en: "Welcome!", pt: "Bem-vindo!", icon: "🤗" }, { en: "to give", pt: "dar", icon: "🎁" }, { en: "half", pt: "metade", icon: "➗" },
    ],
    lines: [
      { who: "jesus", en: "Zacchaeus, come down quickly!", pt: "Zaqueu, desça depressa!" },
      { who: "zaqueu", en: "Me? You know my name?", pt: "Eu? O senhor sabe meu nome?" },
      { who: "jesus", en: "Yes. Today I must stay at your house.", pt: "Sim. Hoje eu preciso ficar na sua casa." },
      { who: "zaqueu", en: "At my house? Welcome, Lord! Please come in.", pt: "Na minha casa? Bem-vindo, Senhor! Por favor, entre." },
      { who: "jesus", en: "Thank you. Your house is very nice.", pt: "Obrigado. Sua casa é muito bonita." },
      { who: "zaqueu", en: "Lord, I give half of my money to the poor.", pt: "Senhor, eu dou metade do meu dinheiro aos pobres." },
      { who: "jesus", en: "Today salvation has come to this house.", pt: "Hoje a salvação chegou a esta casa." },
    ],
    truth: "Jesus chamou Zaqueu pelo nome, hospedou-se em sua casa, e Zaqueu prometeu dar metade dos bens aos pobres e devolver em quádruplo o que tomara (Lucas 19:5-9).",
  },
  {
    id: "c-jesus-4", char: "jesus", unit: "u1", title: "A tempestade no barco", func: "Falar do tempo e acalmar alguém",
    ref: "Marcos 4:35-41", with: "pedro",
    context: "De noite, no barco, vem uma grande tempestade. Jesus dorme na popa.",
    vocab: [
      { en: "wind", pt: "vento", icon: "🌬️" }, { en: "storm", pt: "tempestade", icon: "⛈️" },
      { en: "afraid", pt: "com medo", icon: "😨" }, { en: "Be quiet!", pt: "Silêncio!", icon: "🤫" }, { en: "calm", pt: "calmo", icon: "😌" },
    ],
    lines: [
      { who: "pedro", en: "Master, wake up! There is a big storm!", pt: "Mestre, acorde! Há uma grande tempestade!" },
      { who: "jesus", en: "What is happening?", pt: "O que está acontecendo?" },
      { who: "pedro", en: "The wind is strong and the water is in the boat!", pt: "O vento está forte e a água está no barco!" },
      { who: "jesus", en: "Why are you afraid?", pt: "Por que vocês estão com medo?" },
      { who: "pedro", en: "Because we are going to die!", pt: "Porque nós vamos morrer!" },
      { who: "jesus", en: "Peace! Be quiet!", pt: "Paz! Aquieta-te!" },
      { who: "pedro", en: "Look! The sea is calm now.", pt: "Olha! O mar está calmo agora." },
      { who: "jesus", en: "Where is your faith?", pt: "Onde está a sua fé?" },
    ],
    truth: "Os discípulos acordaram Jesus dizendo \"Mestre, não te importa que pereçamos?\"; ele repreendeu o vento, disse ao mar \"Cala-te, aquieta-te\", e houve grande bonança (Marcos 4:38-39).",
  },
  {
    id: "c-jesus-5", char: "jesus", unit: "u1", title: "Marta e Maria", func: "Tarefas de casa e pedir ajuda",
    ref: "Lucas 10:38-42", with: "marta",
    context: "Marta recebe Jesus em casa e trabalha muito; Maria senta-se para ouvir.",
    vocab: [
      { en: "to cook", pt: "cozinhar", icon: "🍲" }, { en: "busy", pt: "ocupada", icon: "🏃‍♀️" },
      { en: "to help", pt: "ajudar", icon: "🤝" }, { en: "to listen", pt: "ouvir", icon: "👂" }, { en: "Don't worry", pt: "Não se preocupe", icon: "🙂" },
    ],
    lines: [
      { who: "marta", en: "Lord, I am cooking and cleaning all alone!", pt: "Senhor, estou cozinhando e limpando sozinha!" },
      { who: "jesus", en: "Martha, you are very busy today.", pt: "Marta, você está muito ocupada hoje." },
      { who: "marta", en: "Yes! Tell my sister to help me.", pt: "Sim! Diga à minha irmã para me ajudar." },
      { who: "jesus", en: "Martha, Martha, don't worry about many things.", pt: "Marta, Marta, não se preocupe com tantas coisas." },
      { who: "marta", en: "But there is so much work!", pt: "Mas há tanto trabalho!" },
      { who: "jesus", en: "Only one thing is needed.", pt: "Só uma coisa é necessária." },
      { who: "marta", en: "What thing, Lord?", pt: "Que coisa, Senhor?" },
      { who: "jesus", en: "Mary listens to me. She chose the good part.", pt: "Maria me ouve. Ela escolheu a boa parte." },
    ],
    truth: "Marta, ocupada com muito serviço, pediu que Jesus mandasse Maria ajudá-la; Jesus respondeu que uma só coisa é necessária e Maria escolheu a boa parte (Lucas 10:40-42).",
  },
  {
    id: "c-jesus-6", char: "jesus", unit: "u1", title: "O que você quer que eu faça?", func: "Pedir ajuda e oferecer ajuda",
    ref: "Marcos 10:46-52", with: "bartimeu",
    context: "Na saída de Jericó, o cego Bartimeu grita à beira do caminho.",
    vocab: [
      { en: "to see", pt: "ver", icon: "👀" }, { en: "Help me!", pt: "Me ajude!", icon: "🆘" },
      { en: "What do you want?", pt: "O que você quer?", icon: "❓" }, { en: "to go", pt: "ir", icon: "🚶" }, { en: "faith", pt: "fé", icon: "🙏" },
    ],
    lines: [
      { who: "bartimeu", en: "Jesus, Son of David, have mercy on me!", pt: "Jesus, Filho de Davi, tem misericórdia de mim!" },
      { who: "jesus", en: "Call him. Tell him to come here.", pt: "Chamem-no. Digam a ele para vir aqui." },
      { who: "bartimeu", en: "I am here, Master.", pt: "Estou aqui, Mestre." },
      { who: "jesus", en: "What do you want me to do for you?", pt: "O que você quer que eu faça por você?" },
      { who: "bartimeu", en: "Master, I want to see.", pt: "Mestre, eu quero ver." },
      { who: "jesus", en: "Go. Your faith has healed you.", pt: "Vá. A sua fé o curou." },
      { who: "bartimeu", en: "I can see! I can see everything!", pt: "Eu consigo ver! Eu vejo tudo!" },
      { who: "jesus", en: "Come, walk with me.", pt: "Venha, ande comigo." },
    ],
    truth: "Bartimeu gritou \"Jesus, Filho de Davi, tem misericórdia de mim\"; Jesus perguntou \"Que queres que te faça?\", ele disse \"que eu veja\", foi curado e seguiu Jesus pelo caminho (Marcos 10:47-52).",
  },

  // ===================== NOÉ (capítulo 2) =====================
  {
    id: "c-noe-1", char: "noe", unit: "u2", title: "Instruções para a arca", func: "Entender instruções e medidas",
    ref: "Gênesis 6:14-16", with: "voice",
    context: "Deus fala com Noé e explica como construir a arca.",
    vocab: [
      { en: "to build", pt: "construir", icon: "🔨" }, { en: "wood", pt: "madeira", icon: "🪵" },
      { en: "long", pt: "comprido", icon: "📏" }, { en: "door", pt: "porta", icon: "🚪" }, { en: "window", pt: "janela", icon: "🪟" },
    ],
    lines: [
      { who: "voice", en: "Noah, make an ark of wood.", pt: "Noé, faça uma arca de madeira." },
      { who: "noe", en: "An ark, Lord? How big?", pt: "Uma arca, Senhor? De que tamanho?" },
      { who: "voice", en: "Three hundred cubits long and thirty cubits high.", pt: "Trezentos côvados de comprimento e trinta de altura." },
      { who: "noe", en: "That is very big! How many floors?", pt: "É muito grande! Quantos andares?" },
      { who: "voice", en: "Three floors. Put a door on the side.", pt: "Três andares. Ponha uma porta na lateral." },
      { who: "noe", en: "One door on the side. And a window?", pt: "Uma porta na lateral. E uma janela?" },
      { who: "voice", en: "Yes, a window on top. Cover it with pitch.", pt: "Sim, uma janela em cima. Cubra com betume." },
      { who: "noe", en: "I understand. I will do everything you say.", pt: "Entendi. Vou fazer tudo o que o Senhor disser." },
    ],
    truth: "Deus mandou Noé fazer uma arca de madeira de gofer, com 300 côvados de comprimento, 50 de largura e 30 de altura, betumada, com janela, porta lateral e três andares; e Noé fez conforme tudo o que Deus lhe ordenou (Gênesis 6:14-16, 22).",
  },
  {
    id: "c-noe-2", char: "noe", unit: "u2", title: "Comprando a madeira", func: "Comprar e perguntar o preço",
    ref: "Gênesis 6:14, 22", with: "merchant",
    context: "Noé precisa de muita madeira e betume. Ele vai ao mercador.",
    vocab: [
      { en: "I need", pt: "Eu preciso", icon: "🙋" }, { en: "How much is it?", pt: "Quanto custa?", icon: "💰" },
      { en: "a lot of", pt: "muito(a)", icon: "📦" }, { en: "expensive", pt: "caro", icon: "💸" }, { en: "Deal!", pt: "Fechado!", icon: "🤝" },
    ],
    lines: [
      { who: "noe", en: "Good morning! I need some wood.", pt: "Bom dia! Preciso de madeira." },
      { who: "merchant", en: "Good morning. How much wood do you need?", pt: "Bom dia. De quanta madeira o senhor precisa?" },
      { who: "noe", en: "A lot of wood. I am building a very big boat.", pt: "Muita madeira. Estou construindo um barco muito grande." },
      { who: "merchant", en: "A boat? Here, in the desert?", pt: "Um barco? Aqui, no deserto?" },
      { who: "noe", en: "Yes. How much is the wood?", pt: "Sim. Quanto custa a madeira?" },
      { who: "merchant", en: "Ten pieces of silver for each tree.", pt: "Dez peças de prata por árvore." },
      { who: "noe", en: "That is expensive. Eight pieces, and I take fifty trees.", pt: "Está caro. Oito peças, e eu levo cinquenta árvores." },
      { who: "merchant", en: "Fifty trees? Deal! Do you need pitch too?", pt: "Cinquenta árvores? Fechado! Precisa de betume também?" },
      { who: "noe", en: "Yes, please. Thank you very much.", pt: "Sim, por favor. Muito obrigado." },
    ],
    truth: "A Bíblia diz que a arca foi feita de madeira de gofer, betumada por dentro e por fora, e que Noé fez tudo como Deus ordenou (Gênesis 6:14, 22). A negociação com um mercador é uma situação imaginada para praticar compras.",
  },
  {
    id: "c-noe-3", char: "noe", unit: "u2", title: "Os animais de dois em dois", func: "Falar de animais e contar",
    ref: "Gênesis 6:19-20; 7:8-9", with: "sem",
    context: "Os animais chegam à arca. Noé e seu filho Sem organizam a entrada.",
    vocab: [
      { en: "animals", pt: "animais", icon: "🐾" }, { en: "two by two", pt: "de dois em dois", icon: "2️⃣" },
      { en: "lion", pt: "leão", icon: "🦁" }, { en: "bird", pt: "pássaro", icon: "🐦" }, { en: "Count them", pt: "Conte-os", icon: "🔢" },
    ],
    lines: [
      { who: "sem", en: "Look, Noah! The animals are coming!", pt: "Olha, Noé! Os animais estão chegando!" },
      { who: "noe", en: "Yes! Two by two, a male and a female.", pt: "Sim! De dois em dois, um macho e uma fêmea." },
      { who: "sem", en: "Here come two lions and two elephants.", pt: "Aí vêm dois leões e dois elefantes." },
      { who: "noe", en: "Open the door. Let them in slowly.", pt: "Abra a porta. Deixe-os entrar devagar." },
      { who: "sem", en: "And the birds? There are so many birds!", pt: "E os pássaros? Há tantos pássaros!" },
      { who: "noe", en: "Count them. The birds go on the top floor.", pt: "Conte-os. Os pássaros vão para o andar de cima." },
      { who: "sem", en: "Seven pairs of doves. Is that right?", pt: "Sete pares de pombas. Está certo?" },
      { who: "noe", en: "That is right. God takes care of every animal.", pt: "Está certo. Deus cuida de cada animal." },
    ],
    truth: "Deus mandou levar para a arca dois de cada espécie, macho e fêmea, e sete pares dos animais limpos e das aves; os animais entraram de dois em dois, como Deus ordenara a Noé (Gênesis 6:19-20; 7:2-3, 8-9).",
  },
  {
    id: "c-noe-4", char: "noe", unit: "u2", title: "Está chovendo!", func: "Falar do tempo e agir com urgência",
    ref: "Gênesis 7:7-12", with: "esposa",
    context: "As primeiras gotas caem. Noé e sua esposa precisam levar a família para dentro da arca agora.",
    vocab: [
      { en: "It's raining", pt: "Está chovendo", icon: "🌧️" }, { en: "Hurry!", pt: "Depressa!", icon: "🏃" },
      { en: "inside", pt: "para dentro", icon: "🚪" }, { en: "cloud", pt: "nuvem", icon: "☁️" }, { en: "safe", pt: "seguro", icon: "🛡️" },
    ],
    lines: [
      { who: "esposa", en: "Noah, look at the sky! Black clouds!", pt: "Noé, olhe o céu! Nuvens negras!" },
      { who: "noe", en: "It's raining. It's time. Everybody inside!", pt: "Está chovendo. É hora. Todo mundo para dentro!" },
      { who: "esposa", en: "Where are the children?", pt: "Onde estão as crianças?" },
      { who: "noe", en: "They are with the animals. Hurry, please!", pt: "Estão com os animais. Depressa, por favor!" },
      { who: "esposa", en: "The rain is very strong now!", pt: "A chuva está muito forte agora!" },
      { who: "noe", en: "Don't be afraid. We are safe in the ark.", pt: "Não tenha medo. Estamos seguros na arca." },
      { who: "esposa", en: "How long will it rain?", pt: "Por quanto tempo vai chover?" },
      { who: "noe", en: "Forty days and forty nights.", pt: "Quarenta dias e quarenta noites." },
    ],
    truth: "Noé, sua mulher, seus filhos e as noras entraram na arca por causa das águas do dilúvio; sete dias depois choveu sobre a terra quarenta dias e quarenta noites (Gênesis 7:7, 10-12).",
  },
  {
    id: "c-noe-5", char: "noe", unit: "u2", title: "A pomba e a folha", func: "Esperar, contar os dias e dar notícias",
    ref: "Gênesis 8:6-12", with: "sem",
    context: "A chuva parou. Noé abre a janela e solta os pássaros; Sem, seu filho, acompanha tudo.",
    vocab: [
      { en: "to wait", pt: "esperar", icon: "⏳" }, { en: "seven days", pt: "sete dias", icon: "📆" },
      { en: "to come back", pt: "voltar", icon: "↩️" }, { en: "leaf", pt: "folha", icon: "🍃" }, { en: "good news", pt: "boa notícia", icon: "📣" },
    ],
    lines: [
      { who: "sem", en: "Father, the rain stopped. Can we go out?", pt: "Pai, a chuva parou. Podemos sair?" },
      { who: "noe", en: "Not yet. First I will send a dove.", pt: "Ainda não. Primeiro vou enviar uma pomba." },
      { who: "sem", en: "The dove came back. There is no dry land.", pt: "A pomba voltou. Não há terra seca." },
      { who: "noe", en: "Then we wait seven more days.", pt: "Então esperamos mais sete dias." },
      { who: "sem", en: "Look! The dove came back with a leaf!", pt: "Olha! A pomba voltou com uma folha!" },
      { who: "noe", en: "Good news! The trees are dry.", pt: "Boa notícia! As árvores estão secas." },
      { who: "sem", en: "And now, father?", pt: "E agora, pai?" },
      { who: "noe", en: "One more week. Then we can go out.", pt: "Mais uma semana. Depois podemos sair." },
    ],
    truth: "Noé soltou um corvo e depois uma pomba; ela voltou sem pousar, sete dias depois voltou com uma folha de oliveira no bico, e após mais sete dias não voltou mais (Gênesis 8:7-12).",
  },
  {
    id: "c-noe-6", char: "noe", unit: "u2", title: "O arco-íris", func: "Agradecer e falar de promessas",
    ref: "Gênesis 8:15-20; 9:12-17", with: "voice",
    context: "Todos saem da arca. Noé constrói um altar, e Deus faz uma promessa.",
    vocab: [
      { en: "Thank you", pt: "Obrigado", icon: "🙏" }, { en: "promise", pt: "promessa", icon: "🤞" },
      { en: "rainbow", pt: "arco-íris", icon: "🌈" }, { en: "never again", pt: "nunca mais", icon: "🚫" }, { en: "to remember", pt: "lembrar", icon: "🧠" },
    ],
    lines: [
      { who: "voice", en: "Noah, go out of the ark with your family.", pt: "Noé, saia da arca com a sua família." },
      { who: "noe", en: "Thank you, Lord! The earth is dry again.", pt: "Obrigado, Senhor! A terra está seca de novo." },
      { who: "voice", en: "I make a promise to you and to every animal.", pt: "Eu faço uma promessa a você e a cada animal." },
      { who: "noe", en: "What promise, Lord?", pt: "Que promessa, Senhor?" },
      { who: "voice", en: "Never again will a flood destroy the earth.", pt: "Nunca mais um dilúvio destruirá a terra." },
      { who: "noe", en: "How will we remember this promise?", pt: "Como vamos lembrar dessa promessa?" },
      { who: "voice", en: "Look at the cloud. I put my rainbow there.", pt: "Olhe a nuvem. Eu pus meu arco-íris ali." },
      { who: "noe", en: "It is beautiful! Thank you, Lord.", pt: "É lindo! Obrigado, Senhor." },
    ],
    truth: "Deus mandou Noé sair da arca, Noé edificou um altar, e Deus pôs o arco nas nuvens como sinal da aliança de nunca mais destruir a terra com dilúvio (Gênesis 8:15-20; 9:11-13).",
  },

  // ===================== MOISÉS (capítulo 3) =====================
  {
    id: "c-moises-1", char: "moises", unit: "u3", title: "Qual é o seu nome?", func: "Apresentar-se e perguntar o nome",
    ref: "Êxodo 3:1-14", with: "voice",
    context: "No deserto, Moisés vê uma sarça que arde sem se queimar e ouve uma voz.",
    vocab: [
      { en: "What is your name?", pt: "Qual é o seu nome?", icon: "🪪" }, { en: "My name is", pt: "Meu nome é", icon: "🙋‍♂️" },
      { en: "Here I am", pt: "Aqui estou", icon: "📍" }, { en: "shoes", pt: "sandálias", icon: "👡" }, { en: "holy", pt: "santo", icon: "✨" },
    ],
    lines: [
      { who: "voice", en: "Moses! Moses!", pt: "Moisés! Moisés!" },
      { who: "moises", en: "Here I am. Who is speaking?", pt: "Aqui estou. Quem está falando?" },
      { who: "voice", en: "Take off your shoes. This is holy ground.", pt: "Tire as sandálias. Este é chão santo." },
      { who: "moises", en: "Yes. But who are you?", pt: "Sim. Mas quem é o senhor?" },
      { who: "voice", en: "I am the God of Abraham, Isaac and Jacob.", pt: "Eu sou o Deus de Abraão, Isaque e Jacó." },
      { who: "moises", en: "If the people ask me, what is your name?", pt: "Se o povo me perguntar, qual é o seu nome?" },
      { who: "voice", en: "I AM WHO I AM. Tell them: I AM sent me.", pt: "EU SOU O QUE SOU. Diga-lhes: EU SOU me enviou." },
      { who: "moises", en: "I will tell them. Lord, here I am.", pt: "Eu direi a eles. Senhor, aqui estou." },
    ],
    truth: "Deus chamou Moisés na sarça ardente, mandou tirar as sandálias, apresentou-se como o Deus de Abraão, Isaque e Jacó e revelou seu nome: EU SOU O QUE SOU (Êxodo 3:4-6, 13-14).",
  },
  {
    id: "c-moises-2", char: "moises", unit: "u3", title: "Deixe o meu povo ir", func: "Fazer um pedido e lidar com um não",
    ref: "Êxodo 5:1-2; 7:14-16", with: "pharaoh",
    context: "Moisés e Arão vão ao palácio pedir a liberdade de Israel.",
    vocab: [
      { en: "Let my people go", pt: "Deixe o meu povo ir", icon: "🕊️" }, { en: "No", pt: "Não", icon: "🙅" },
      { en: "to work", pt: "trabalhar", icon: "🧱" }, { en: "again", pt: "de novo", icon: "🔁" }, { en: "tomorrow", pt: "amanhã", icon: "📅" },
    ],
    lines: [
      { who: "moises", en: "Pharaoh, the Lord says: let my people go.", pt: "Faraó, o Senhor diz: deixe o meu povo ir." },
      { who: "pharaoh", en: "Who is the Lord? I do not know him.", pt: "Quem é o Senhor? Eu não o conheço." },
      { who: "moises", en: "He is the God of Israel. Please, let us go.", pt: "Ele é o Deus de Israel. Por favor, deixe-nos ir." },
      { who: "pharaoh", en: "No! Your people must work. Go back to work!", pt: "Não! O seu povo precisa trabalhar. Voltem ao trabalho!" },
      { who: "moises", en: "If you say no, God will send a sign.", pt: "Se o senhor disser não, Deus enviará um sinal." },
      { who: "pharaoh", en: "I say no. Now leave my palace.", pt: "Eu digo não. Agora saia do meu palácio." },
      { who: "moises", en: "Tomorrow morning I will come again.", pt: "Amanhã de manhã eu voltarei." },
    ],
    truth: "Moisés e Arão disseram a Faraó \"Assim diz o Senhor: deixa ir o meu povo\"; Faraó respondeu \"Quem é o Senhor? Não o conheço\" e aumentou o trabalho do povo (Êxodo 5:1-2, 6-9).",
  },
  {
    id: "c-moises-3", char: "moises", unit: "u3", title: "Rãs por toda parte", func: "Descrever um problema",
    ref: "Êxodo 8:1-13", with: "pharaoh",
    context: "A praga das rãs cobre o Egito. Faraó chama Moisés.",
    vocab: [
      { en: "problem", pt: "problema", icon: "⚠️" }, { en: "frog", pt: "rã", icon: "🐸" },
      { en: "everywhere", pt: "por toda parte", icon: "🌍" }, { en: "kitchen", pt: "cozinha", icon: "🍳" }, { en: "to pray", pt: "orar", icon: "🙏" },
    ],
    lines: [
      { who: "pharaoh", en: "Moses, I have a big problem!", pt: "Moisés, eu tenho um grande problema!" },
      { who: "moises", en: "What is the problem?", pt: "Qual é o problema?" },
      { who: "pharaoh", en: "Frogs! There are frogs everywhere!", pt: "Rãs! Há rãs por toda parte!" },
      { who: "moises", en: "Where are they?", pt: "Onde elas estão?" },
      { who: "pharaoh", en: "In my bed, in my kitchen, in my bread!", pt: "Na minha cama, na minha cozinha, no meu pão!" },
      { who: "moises", en: "Pray to the Lord, and the frogs will go.", pt: "Ore ao Senhor, e as rãs irão embora." },
      { who: "pharaoh", en: "Pray for me! Then I will let your people go.", pt: "Ore por mim! Então deixarei o seu povo ir." },
      { who: "moises", en: "Tomorrow the frogs will be gone.", pt: "Amanhã as rãs terão ido embora." },
    ],
    truth: "As rãs subiram e cobriram o Egito, entrando nas casas, nos quartos, nas camas e nas amassadeiras; Faraó pediu que Moisés orasse, e as rãs morreram no dia seguinte (Êxodo 8:3, 6, 8-13).",
  },
  {
    id: "c-moises-4", char: "moises", unit: "u3", title: "A ceia da Páscoa", func: "Preparar comida e dar instruções na cozinha",
    ref: "Êxodo 12:3-11", with: "arao",
    context: "Na última noite no Egito, cada família prepara o cordeiro da Páscoa.",
    vocab: [
      { en: "lamb", pt: "cordeiro", icon: "🐑" }, { en: "to roast", pt: "assar", icon: "🔥" },
      { en: "dinner", pt: "jantar", icon: "🍽️" }, { en: "quickly", pt: "rapidamente", icon: "⚡" }, { en: "ready", pt: "pronto", icon: "✅" },
    ],
    lines: [
      { who: "arao", en: "Moses, what do we eat tonight?", pt: "Moisés, o que comemos hoje à noite?" },
      { who: "moises", en: "Each family takes a lamb, one year old.", pt: "Cada família pega um cordeiro de um ano." },
      { who: "arao", en: "How do we cook it?", pt: "Como o cozinhamos?" },
      { who: "moises", en: "Roast it with fire, with bread and bitter herbs.", pt: "Asse no fogo, com pão e ervas amargas." },
      { who: "arao", en: "And the blood of the lamb?", pt: "E o sangue do cordeiro?" },
      { who: "moises", en: "Put it on the door of the house.", pt: "Ponha nas portas da casa." },
      { who: "arao", en: "The dinner is ready. Can we sit down?", pt: "O jantar está pronto. Podemos sentar?" },
      { who: "moises", en: "No. Eat quickly, with your shoes on. Tonight we leave!", pt: "Não. Comam depressa, calçados. Hoje à noite partimos!" },
    ],
    truth: "Cada família tomou um cordeiro sem defeito, pôs o sangue nas ombreiras das portas e comeu a carne assada no fogo com pães asmos e ervas amargas, apressadamente, com as sandálias nos pés (Êxodo 12:3-11).",
  },
  {
    id: "c-moises-5", char: "moises", unit: "u3", title: "Avancem!", func: "Dar direções e encorajar",
    ref: "Êxodo 14:10-22", with: "josue",
    context: "O mar está à frente e o exército de Faraó atrás. O povo tem medo.",
    vocab: [
      { en: "Go forward", pt: "Avancem", icon: "⬆️" }, { en: "behind", pt: "atrás", icon: "⬅️" },
      { en: "in front of", pt: "na frente de", icon: "➡️" }, { en: "Don't be afraid", pt: "Não tenham medo", icon: "💪" }, { en: "dry", pt: "seco", icon: "🏜️" },
    ],
    lines: [
      { who: "josue", en: "Moses! The Egyptians are behind us!", pt: "Moisés! Os egípcios estão atrás de nós!" },
      { who: "moises", en: "Don't be afraid. Stand still and watch.", pt: "Não tenham medo. Fiquem parados e observem." },
      { who: "josue", en: "But the sea is in front of us!", pt: "Mas o mar está na nossa frente!" },
      { who: "moises", en: "The Lord will fight for you today.", pt: "O Senhor lutará por vocês hoje." },
      { who: "josue", en: "What do we do now?", pt: "O que fazemos agora?" },
      { who: "moises", en: "Go forward! Walk through the sea on dry ground.", pt: "Avancem! Andem pelo mar em terra seca." },
      { who: "josue", en: "The water is a wall on the right and on the left!", pt: "A água é um muro à direita e à esquerda!" },
      { who: "moises", en: "Keep walking. Don't stop until the other side.", pt: "Continuem andando. Não parem até o outro lado." },
    ],
    truth: "Moisés disse ao povo \"não temais, estai quietos e vede o livramento do Senhor\", o Senhor mandou \"dize aos filhos de Israel que marchem\", e eles passaram pelo meio do mar em seco, as águas como muro à direita e à esquerda (Êxodo 14:13-16, 22).",
  },
  {
    id: "c-moises-6", char: "moises", unit: "u3", title: "Fome e sede no deserto", func: "Falar de fome, sede e necessidades",
    ref: "Êxodo 16:2-4, 13-15; 17:1-6", with: "povo",
    context: "No deserto, o povo reclama que não há pão nem água.",
    vocab: [
      { en: "I'm hungry", pt: "Estou com fome", icon: "🍽️" }, { en: "I'm thirsty", pt: "Estou com sede", icon: "🥤" },
      { en: "water", pt: "água", icon: "💧" }, { en: "every morning", pt: "toda manhã", icon: "🌄" }, { en: "rock", pt: "rocha", icon: "🪨" },
    ],
    lines: [
      { who: "povo", en: "Moses, we are hungry! There is no bread here.", pt: "Moisés, estamos com fome! Não há pão aqui." },
      { who: "moises", en: "The Lord will give you bread from heaven.", pt: "O Senhor dará a vocês pão do céu." },
      { who: "povo", en: "Bread from heaven? When?", pt: "Pão do céu? Quando?" },
      { who: "moises", en: "Every morning. Take only what you need for one day.", pt: "Toda manhã. Peguem só o que precisam para um dia." },
      { who: "povo", en: "And we are thirsty! Give us water!", pt: "E estamos com sede! Dê-nos água!" },
      { who: "moises", en: "Lord, what do I do with this people?", pt: "Senhor, o que eu faço com este povo?" },
      { who: "povo", en: "Look! Water is coming out of the rock!", pt: "Olha! Água está saindo da rocha!" },
      { who: "moises", en: "Drink. The Lord takes care of you.", pt: "Bebam. O Senhor cuida de vocês." },
    ],
    truth: "O povo murmurou por pão e Deus fez chover maná toda manhã, cada um colhendo o necessário para o dia; em Refidim o povo teve sede, Moisés feriu a rocha em Horebe e saiu água (Êxodo 16:4, 14-18; 17:3-6).",
  },

  // ===================== DAVI (capítulo 4) =====================
  {
    id: "c-davi-1", char: "davi", unit: "u4", title: "O caçula que cuida das ovelhas", func: "Falar da família e das profissões",
    ref: "1 Samuel 16:1-13", with: "samuel",
    context: "Samuel chega a Belém para ungir um novo rei. O caçula está no campo.",
    vocab: [
      { en: "brother", pt: "irmão", icon: "👦" }, { en: "the youngest", pt: "o mais novo", icon: "🧒" },
      { en: "shepherd", pt: "pastor", icon: "🐑" }, { en: "job", pt: "trabalho", icon: "💼" }, { en: "Nice to meet you", pt: "Prazer em conhecê-lo", icon: "🤝" },
    ],
    lines: [
      { who: "samuel", en: "Are these all your sons, Jesse?", pt: "Estes são todos os seus filhos, Jessé?" },
      { who: "jesse", en: "No. The youngest is in the field with the sheep.", pt: "Não. O mais novo está no campo com as ovelhas." },
      { who: "samuel", en: "Call him. We will not sit down until he comes.", pt: "Chame-o. Não vamos sentar até ele chegar." },
      { who: "davi", en: "Good afternoon. My name is David. Who are you?", pt: "Boa tarde. Meu nome é Davi. Quem é o senhor?" },
      { who: "samuel", en: "I am Samuel, the prophet. Nice to meet you, David.", pt: "Eu sou Samuel, o profeta. Prazer em conhecê-lo, Davi." },
      { who: "davi", en: "Nice to meet you too. I am a shepherd.", pt: "Prazer em conhecê-lo também. Eu sou pastor." },
      { who: "samuel", en: "Do you have brothers?", pt: "Você tem irmãos?" },
      { who: "davi", en: "Yes, I have seven brothers. I am the youngest.", pt: "Sim, tenho sete irmãos. Eu sou o mais novo." },
      { who: "samuel", en: "The Lord looks at the heart. You will be king.", pt: "O Senhor olha para o coração. Você será rei." },
    ],
    truth: "Samuel viu os sete filhos de Jessé, mas o Senhor não escolheu nenhum; o caçula, Davi, apascentava as ovelhas, foi chamado e Samuel o ungiu no meio dos irmãos (1 Samuel 16:6-13).",
  },
  {
    id: "c-davi-2", char: "davi", unit: "u4", title: "Recado para os irmãos", func: "Fazer um recado e levar comida",
    ref: "1 Samuel 17:17-20", with: "jesse",
    context: "Jessé manda Davi levar comida aos irmãos, que estão no exército de Saul.",
    vocab: [
      { en: "to take (something to)", pt: "levar", icon: "🎒" }, { en: "cheese", pt: "queijo", icon: "🧀" },
      { en: "early", pt: "cedo", icon: "⏰" }, { en: "How are they?", pt: "Como eles estão?", icon: "🤔" }, { en: "camp", pt: "acampamento", icon: "⛺" },
    ],
    lines: [
      { who: "jesse", en: "David, take this food to your brothers.", pt: "Davi, leve esta comida aos seus irmãos." },
      { who: "davi", en: "Of course, father. What do I take?", pt: "Claro, pai. O que eu levo?" },
      { who: "jesse", en: "Ten loaves of bread, some grain and ten cheeses.", pt: "Dez pães, um pouco de grão e dez queijos." },
      { who: "davi", en: "Ten cheeses? Who are the cheeses for?", pt: "Dez queijos? Para quem são os queijos?" },
      { who: "jesse", en: "For the captain. And see how your brothers are.", pt: "Para o capitão. E veja como estão seus irmãos." },
      { who: "davi", en: "When do I go?", pt: "Quando eu vou?" },
      { who: "jesse", en: "Early in the morning. The camp is far.", pt: "De manhã cedo. O acampamento é longe." },
      { who: "davi", en: "I will go early and bring news back.", pt: "Vou cedo e trago notícias de volta." },
    ],
    truth: "Jessé mandou Davi levar aos irmãos um efa de grão tostado e dez pães, e dez queijos ao capitão, e saber como estavam; Davi partiu de madrugada e chegou ao acampamento (1 Samuel 17:17-20).",
  },
  {
    id: "c-davi-3", char: "davi", unit: "u4", title: "Diante de Golias", func: "Enfrentar um desafio e se apresentar com coragem",
    ref: "1 Samuel 17:41-50", with: "goliath",
    context: "O gigante Golias zomba do exército de Israel. Davi vai ao seu encontro com uma funda.",
    vocab: [
      { en: "Who are you?", pt: "Quem é você?", icon: "❓" }, { en: "sword", pt: "espada", icon: "⚔️" },
      { en: "stone", pt: "pedra", icon: "🪨" }, { en: "in the name of", pt: "em nome de", icon: "📢" }, { en: "small", pt: "pequeno", icon: "🤏" },
    ],
    lines: [
      { who: "goliath", en: "Who are you, little boy?", pt: "Quem é você, garotinho?" },
      { who: "davi", en: "I am David, the son of Jesse.", pt: "Eu sou Davi, filho de Jessé." },
      { who: "goliath", en: "Where is your sword? Do you have a stick?", pt: "Onde está a sua espada? Você tem um pau?" },
      { who: "davi", en: "I have five stones and a sling.", pt: "Tenho cinco pedras e uma funda." },
      { who: "goliath", en: "Stones? Come here, and I will feed you to the birds!", pt: "Pedras? Venha cá, e eu darei você aos pássaros!" },
      { who: "davi", en: "You come with a sword. I come in the name of the Lord.", pt: "Você vem com espada. Eu venho em nome do Senhor." },
      { who: "goliath", en: "The Lord? Ha! I am not afraid of you.", pt: "O Senhor? Ha! Eu não tenho medo de você." },
      { who: "davi", en: "Today everyone will know that there is a God in Israel.", pt: "Hoje todos saberão que há um Deus em Israel." },
    ],
    truth: "Golias desprezou Davi por ser jovem e o ameaçou; Davi respondeu \"tu vens a mim com espada, mas eu vou a ti em nome do Senhor dos Exércitos\", tirou uma pedra da funda e derrubou o gigante (1 Samuel 17:42-50).",
  },
  {
    id: "c-davi-4", char: "davi", unit: "u4", title: "Meu melhor amigo", func: "Falar de amizade e dar presentes",
    ref: "1 Samuel 18:1-4", with: "jonatas",
    context: "Depois da vitória, Jônatas, o filho do rei, faz amizade com Davi.",
    vocab: [
      { en: "friend", pt: "amigo", icon: "🧑‍🤝‍🧑" }, { en: "gift", pt: "presente", icon: "🎁" },
      { en: "robe", pt: "manto", icon: "🧥" }, { en: "This is for you", pt: "Isto é para você", icon: "👉" }, { en: "forever", pt: "para sempre", icon: "♾️" },
    ],
    lines: [
      { who: "jonatas", en: "David, you are very brave. I want to be your friend.", pt: "Davi, você é muito corajoso. Quero ser seu amigo." },
      { who: "davi", en: "Thank you, Jonathan. I want to be your friend too.", pt: "Obrigado, Jônatas. Eu também quero ser seu amigo." },
      { who: "jonatas", en: "I have a gift for you. This is my robe.", pt: "Tenho um presente para você. Este é o meu manto." },
      { who: "davi", en: "Your robe? It is beautiful! Thank you very much.", pt: "Seu manto? É lindo! Muito obrigado." },
      { who: "jonatas", en: "And my sword and my bow. They are yours.", pt: "E minha espada e meu arco. Eles são seus." },
      { who: "davi", en: "You are a true friend, Jonathan.", pt: "Você é um amigo de verdade, Jônatas." },
      { who: "jonatas", en: "Friends forever?", pt: "Amigos para sempre?" },
      { who: "davi", en: "Friends forever. God is with us.", pt: "Amigos para sempre. Deus está conosco." },
    ],
    truth: "A alma de Jônatas se ligou à de Davi; eles fizeram aliança, e Jônatas deu a Davi o seu manto, as vestes, a espada, o arco e o cinto (1 Samuel 18:1-4).",
  },
  {
    id: "c-davi-5", char: "davi", unit: "u4", title: "Música para o rei", func: "Falar de música e de sentimentos",
    ref: "1 Samuel 16:14-23", with: "saul",
    context: "O rei Saul está triste e sem paz. Chamam Davi para tocar harpa.",
    vocab: [
      { en: "to play (music)", pt: "tocar", icon: "🎶" }, { en: "harp", pt: "harpa", icon: "🎵" },
      { en: "sad", pt: "triste", icon: "😢" }, { en: "better", pt: "melhor", icon: "📈" }, { en: "song", pt: "canção", icon: "🎤" },
    ],
    lines: [
      { who: "saul", en: "I feel sad and tired. Nothing helps me.", pt: "Eu me sinto triste e cansado. Nada me ajuda." },
      { who: "davi", en: "My king, may I play the harp for you?", pt: "Meu rei, posso tocar harpa para o senhor?" },
      { who: "saul", en: "You play the harp? Yes, please play.", pt: "Você toca harpa? Sim, por favor, toque." },
      { who: "davi", en: "This song is about the Lord, my shepherd.", pt: "Esta canção é sobre o Senhor, meu pastor." },
      { who: "saul", en: "Your music is beautiful. I feel better now.", pt: "Sua música é linda. Eu me sinto melhor agora." },
      { who: "davi", en: "I am glad. Music brings peace.", pt: "Fico feliz. A música traz paz." },
      { who: "saul", en: "Stay here. Play for me every day.", pt: "Fique aqui. Toque para mim todos os dias." },
      { who: "davi", en: "It is an honor, my king.", pt: "É uma honra, meu rei." },
    ],
    truth: "Um espírito mau atormentava Saul; os servos indicaram Davi, filho de Jessé, que sabia tocar; quando Davi tocava a harpa, Saul sentia alívio e ficava melhor (1 Samuel 16:14-23).",
  },
  {
    id: "c-davi-6", char: "davi", unit: "u4", title: "Um lugar à mesa do rei", func: "Convidar para jantar e receber com bondade",
    ref: "2 Samuel 9:1-13", with: "mefibosete",
    context: "Já rei, Davi procura alguém da família de Jônatas para mostrar bondade.",
    vocab: [
      { en: "Don't be afraid", pt: "Não tenha medo", icon: "🤗" }, { en: "to eat with", pt: "comer com", icon: "🍽️" },
      { en: "table", pt: "mesa", icon: "🪑" }, { en: "every day", pt: "todos os dias", icon: "📆" }, { en: "kindness", pt: "bondade", icon: "💚" },
    ],
    lines: [
      { who: "mefibosete", en: "My king, I am your servant.", pt: "Meu rei, eu sou seu servo." },
      { who: "davi", en: "Don't be afraid. Are you Jonathan's son?", pt: "Não tenha medo. Você é filho de Jônatas?" },
      { who: "mefibosete", en: "Yes, I am Mephibosheth. Why do you call me?", pt: "Sim, eu sou Mefibosete. Por que o senhor me chama?" },
      { who: "davi", en: "I want to show you kindness, for your father.", pt: "Quero mostrar bondade a você, por causa do seu pai." },
      { who: "mefibosete", en: "Kindness to me? I am nobody.", pt: "Bondade comigo? Eu não sou ninguém." },
      { who: "davi", en: "You will eat at my table every day.", pt: "Você comerá à minha mesa todos os dias." },
      { who: "mefibosete", en: "At the king's table? Thank you, my king!", pt: "À mesa do rei? Obrigado, meu rei!" },
      { who: "davi", en: "Welcome to my house. Dinner is at six.", pt: "Bem-vindo à minha casa. O jantar é às seis." },
    ],
    truth: "Davi perguntou se restava alguém da casa de Saul para usar de bondade por amor de Jônatas; achou Mefibosete, coxo dos pés, devolveu-lhe as terras e disse que ele comeria sempre à mesa do rei (2 Samuel 9:1-13).",
  },
];
