// BíbliaLearn — Cenas do dia a dia (parte 2): Isaías, José, Daniel, Pedro
// Mesmo esquema de scenes.js. Cada cena parte de um episódio real e usa inglês A1/A2 do cotidiano.

Object.assign(SCENE_EXTRAS, {
  atalaia: { name: "Atalaia", gender: "male", emoji: "🔭", voice: "josh" },
  sedento: { name: "Homem com sede", gender: "male", emoji: "🥵", voice: "paul" },
  mordomo: { name: "Mordomo do palácio", gender: "male", emoji: "🍽️", voice: "jeremy" },
  oficial: { name: "Oficial do rei", gender: "male", emoji: "📋", voice: "antoni" },
});

SCENES.push(
  // ===================== ISAÍAS (capítulo 5) =====================
  {
    id: "c-isaias-1", char: "isaias", unit: "u5", title: "Eis-me aqui, envia-me", func: "Oferecer-se para uma tarefa",
    ref: "Isaías 6:1-13", with: "voice",
    context: "No templo, Isaías vê o Senhor no trono. Um serafim toca seus lábios com uma brasa. Então ouve uma pergunta.",
    vocab: [
      { en: "Who?", pt: "Quem?", icon: "❓" }, { en: "to send", pt: "enviar", icon: "📨" },
      { en: "Here I am", pt: "Eis-me aqui", icon: "🙋" }, { en: "ready", pt: "pronto", icon: "✅" }, { en: "How long?", pt: "Até quando?", icon: "⏳" },
    ],
    lines: [
      { who: "isaias", en: "I am not ready. My lips are unclean.", pt: "Eu não estou pronto. Meus lábios são impuros." },
      { who: "anjo", en: "This coal touched your lips. Your sin is gone.", pt: "Esta brasa tocou seus lábios. Seu pecado se foi." },
      { who: "voice", en: "Whom shall I send? Who will go for us?", pt: "A quem enviarei? Quem irá por nós?" },
      { who: "isaias", en: "Here I am. Send me!", pt: "Eis-me aqui. Envia-me!" },
      { who: "voice", en: "Go and speak to this people.", pt: "Vá e fale a este povo." },
      { who: "isaias", en: "How long, Lord?", pt: "Até quando, Senhor?" },
      { who: "voice", en: "Until the cities are empty. But a holy seed will remain.", pt: "Até que as cidades fiquem vazias. Mas uma semente santa ficará." },
      { who: "isaias", en: "Yes, Lord. I am ready. I will go today.", pt: "Sim, Senhor. Estou pronto. Vou hoje." },
    ],
    truth: "No ano da morte do rei Uzias, Isaías viu o Senhor no trono, disse \"ai de mim, homem de lábios impuros\", um serafim tocou seus lábios com uma brasa, e à pergunta \"a quem enviarei?\" ele respondeu \"eis-me aqui, envia-me a mim\" (Isaías 6:1-8).",
  },
  {
    id: "c-isaias-2", char: "isaias", unit: "u5", title: "Fique calmo, rei", func: "Acalmar alguém com medo e dar uma notícia",
    ref: "Isaías 7:1-14", with: "acaz",
    context: "Dois reis marcham contra Jerusalém. O rei Acaz treme de medo perto do aqueduto. Isaías vai falar com ele.",
    vocab: [
      { en: "Keep calm", pt: "Fique calmo", icon: "😌" }, { en: "afraid", pt: "com medo", icon: "😨" },
      { en: "army", pt: "exército", icon: "⚔️" }, { en: "a sign", pt: "um sinal", icon: "🔆" }, { en: "It will not happen", pt: "Não vai acontecer", icon: "🚫" },
    ],
    lines: [
      { who: "acaz", en: "Isaiah, two kings are coming to attack us. I am afraid.", pt: "Isaías, dois reis vêm nos atacar. Estou com medo." },
      { who: "isaias", en: "Keep calm, my king. Don't be afraid.", pt: "Fique calmo, meu rei. Não tenha medo." },
      { who: "acaz", en: "How can I be calm? Their armies are big.", pt: "Como posso ficar calmo? Os exércitos deles são grandes." },
      { who: "isaias", en: "Those two kings are only two smoking sticks. It will not happen.", pt: "Esses dois reis são só dois tições fumegantes. Não vai acontecer." },
      { who: "acaz", en: "How do you know?", pt: "Como você sabe?" },
      { who: "isaias", en: "Ask the Lord for a sign. Anything you want.", pt: "Peça um sinal ao Senhor. O que você quiser." },
      { who: "acaz", en: "No. I will not ask for a sign.", pt: "Não. Não vou pedir sinal." },
      { who: "isaias", en: "Then the Lord himself will give you a sign: a virgin will have a son, and his name will be Immanuel.", pt: "Então o próprio Senhor lhe dará um sinal: uma virgem terá um filho, e o nome dele será Emanuel." },
      { who: "acaz", en: "Immanuel... God with us.", pt: "Emanuel... Deus conosco." },
    ],
    truth: "Rezim e Peca subiram contra Jerusalém; o coração de Acaz tremeu como as árvores ao vento; o Senhor mandou Isaías dizer \"acautela-te, aquieta-te, não temas\", ofereceu um sinal que Acaz recusou, e então anunciou: \"a virgem conceberá e dará à luz um filho, e lhe chamará Emanuel\" (Isaías 7:1-14).",
  },
  {
    id: "c-isaias-3", char: "isaias", unit: "u5", title: "Consolai o meu povo", func: "Consolar alguém e dar uma boa notícia",
    ref: "Isaías 40:1-11, 28-31", with: "voice",
    context: "O povo está cansado e sem esperança. Deus dá a Isaías uma mensagem de consolo para Jerusalém.",
    vocab: [
      { en: "to comfort", pt: "consolar", icon: "🤗" }, { en: "It's over", pt: "Acabou", icon: "🏁" },
      { en: "weak", pt: "fraco", icon: "😓" }, { en: "forever", pt: "para sempre", icon: "♾️" }, { en: "new strength", pt: "novas forças", icon: "💪" },
    ],
    lines: [
      { who: "voice", en: "Comfort my people. Speak kindly to Jerusalem.", pt: "Consolai o meu povo. Falai com carinho a Jerusalém." },
      { who: "isaias", en: "What should I say to them, Lord?", pt: "O que devo dizer a eles, Senhor?" },
      { who: "voice", en: "Tell them: your hard time is over.", pt: "Diga-lhes: o tempo difícil acabou." },
      { who: "isaias", en: "The people feel weak, like grass.", pt: "O povo se sente fraco, como a erva." },
      { who: "voice", en: "Grass dries and flowers fall, but my word stands forever.", pt: "A erva seca e a flor cai, mas a minha palavra permanece para sempre." },
      { who: "isaias", en: "Then I will go up the mountain and shout the good news.", pt: "Então vou subir ao monte e gritar a boa notícia." },
      { who: "voice", en: "Say to the cities: Here is your God!", pt: "Diga às cidades: Eis aqui o vosso Deus!" },
      { who: "isaias", en: "He comes like a shepherd. He carries the lambs in his arms.", pt: "Ele vem como um pastor. Ele carrega os cordeiros nos braços." },
      { who: "voice", en: "Yes. Those who wait for me will get new strength.", pt: "Sim. Os que esperam em mim terão novas forças." },
    ],
    truth: "\"Consolai, consolai o meu povo\"; toda carne é erva, mas a palavra do nosso Deus subsiste eternamente; \"eis aqui o vosso Deus\"; ele apascenta como pastor e leva os cordeiros no colo; os que esperam no Senhor renovam as forças (Isaías 40:1-11, 31).",
  },
  {
    id: "c-isaias-4", char: "isaias", unit: "u5", title: "Como o senhor se sente?", func: "Falar de saúde e visitar um doente",
    ref: "Isaías 38:1-8, 21", with: "ezequias",
    context: "O rei Ezequias está doente, à beira da morte. Isaías vai ao palácio levar a palavra do Senhor.",
    vocab: [
      { en: "How do you feel?", pt: "Como o senhor se sente?", icon: "🩺" }, { en: "sick", pt: "doente", icon: "🤒" },
      { en: "to get better", pt: "melhorar", icon: "😊" }, { en: "fifteen years", pt: "quinze anos", icon: "🕰️" }, { en: "tears", pt: "lágrimas", icon: "😢" },
    ],
    lines: [
      { who: "isaias", en: "Good afternoon, my king. How do you feel today?", pt: "Boa tarde, meu rei. Como o senhor se sente hoje?" },
      { who: "ezequias", en: "Very sick. I have a bad sore.", pt: "Muito doente. Tenho uma ferida feia." },
      { who: "isaias", en: "The Lord says: put your house in order. This sickness is serious.", pt: "O Senhor diz: põe a tua casa em ordem. Esta doença é grave." },
      { who: "ezequias", en: "Please, Lord, remember me. I served you with all my heart.", pt: "Por favor, Senhor, lembra-te de mim. Eu te servi de todo o coração." },
      { who: "isaias", en: "Wait... The Lord heard your prayer and saw your tears.", pt: "Espere... O Senhor ouviu a sua oração e viu as suas lágrimas." },
      { who: "ezequias", en: "What does he say?", pt: "O que ele diz?" },
      { who: "isaias", en: "You will get better. He adds fifteen years to your life.", pt: "O senhor vai melhorar. Ele acrescenta quinze anos à sua vida." },
      { who: "ezequias", en: "Fifteen years! Thank you, Lord!", pt: "Quinze anos! Obrigado, Senhor!" },
      { who: "isaias", en: "Put figs on the wound. And look: the shadow goes back ten steps.", pt: "Ponha figos na ferida. E veja: a sombra volta dez degraus." },
    ],
    truth: "Ezequias adoeceu de morte; Isaías disse \"põe em ordem a tua casa\"; o rei orou e chorou muito; o Senhor mandou Isaías voltar: \"ouvi a tua oração, vi as tuas lágrimas, acrescento quinze anos à tua vida\", deu o sinal da sombra que recuou dez graus e mandou uma pasta de figos para a úlcera (Isaías 38:1-8, 21).",
  },
  {
    id: "c-isaias-5", char: "isaias", unit: "u5", title: "Comprem sem dinheiro", func: "No mercado: perguntar o preço e receber de graça",
    ref: "Isaías 55:1-3", with: "sedento",
    context: "Como um vendedor na feira, Isaías chama quem tem sede e fome. Mas o preço é uma surpresa.",
    vocab: [
      { en: "thirsty", pt: "com sede", icon: "🥤" }, { en: "money", pt: "dinheiro", icon: "💰" },
      { en: "How much does it cost?", pt: "Quanto custa?", icon: "🏷️" }, { en: "free", pt: "de graça", icon: "🆓" }, { en: "milk", pt: "leite", icon: "🥛" },
    ],
    lines: [
      { who: "isaias", en: "Come! Everyone who is thirsty, come to the water!", pt: "Venham! Todos os que têm sede, venham à água!" },
      { who: "sedento", en: "I am thirsty and hungry, but I have no money.", pt: "Estou com sede e com fome, mas não tenho dinheiro." },
      { who: "isaias", en: "Come, buy and eat. Buy wine and milk without money.", pt: "Venha, compre e coma. Compre vinho e leite sem dinheiro." },
      { who: "sedento", en: "Without money? How much does it cost?", pt: "Sem dinheiro? Quanto custa?" },
      { who: "isaias", en: "It costs nothing. It is free.", pt: "Não custa nada. É de graça." },
      { who: "sedento", en: "Why do I spend my money on things that are not bread?", pt: "Por que eu gasto meu dinheiro com coisas que não são pão?" },
      { who: "isaias", en: "Listen to me and eat what is good.", pt: "Ouça-me e coma o que é bom." },
      { who: "sedento", en: "I am coming. Give me water, please.", pt: "Estou indo. Dê-me água, por favor." },
      { who: "isaias", en: "Come to the Lord, and your soul will live.", pt: "Venha ao Senhor, e a sua alma viverá." },
    ],
    truth: "\"Ó vós, todos os que tendes sede, vinde às águas; e os que não tendes dinheiro, vinde, comprai e comei; comprai vinho e leite sem dinheiro e sem preço. Por que gastais o dinheiro naquilo que não é pão?\" (Isaías 55:1-3).",
  },
  {
    id: "c-isaias-6", char: "isaias", unit: "u5", title: "Boas notícias na montanha", func: "Dar boas notícias e comemorar",
    ref: "Isaías 52:7-10", with: "atalaia",
    context: "Do muro de Jerusalém, o atalaia vê alguém correndo pelos montes. Isaías explica quem é.",
    vocab: [
      { en: "good news", pt: "boa notícia", icon: "📣" }, { en: "messenger", pt: "mensageiro", icon: "🏃" },
      { en: "quickly", pt: "depressa", icon: "⚡" }, { en: "Really?", pt: "Sério?", icon: "😮" }, { en: "to sing", pt: "cantar", icon: "🎶" },
    ],
    lines: [
      { who: "atalaia", en: "Look! Someone is running on the mountain.", pt: "Olhe! Alguém está correndo na montanha." },
      { who: "isaias", en: "It is a messenger. He brings good news.", pt: "É um mensageiro. Ele traz boa notícia." },
      { who: "atalaia", en: "What news? Tell me quickly!", pt: "Que notícias? Diga rápido!" },
      { who: "isaias", en: "Peace! Salvation! Your God reigns!", pt: "Paz! Salvação! O seu Deus reina!" },
      { who: "atalaia", en: "Really? The Lord is coming back to Zion?", pt: "Sério? O Senhor está voltando a Sião?" },
      { who: "isaias", en: "Yes. Lift up your voice and sing together.", pt: "Sim. Levantem a voz e cantem juntos." },
      { who: "atalaia", en: "This is the best news of my life.", pt: "Esta é a melhor notícia da minha vida." },
      { who: "isaias", en: "Sing for joy, Jerusalem! The Lord comforts his people.", pt: "Cante de alegria, Jerusalém! O Senhor consola o seu povo." },
    ],
    truth: "\"Quão formosos são sobre os montes os pés do que anuncia as boas-novas, que faz ouvir a paz, que anuncia a salvação, que diz a Sião: o teu Deus reina! Os teus atalaias levantam a voz, juntamente exultam\" (Isaías 52:7-9).",
  },

  // ===================== JOSÉ (capítulo 6) =====================
  {
    id: "c-jose-1", char: "jose", unit: "u6", title: "A túnica e o sonho", func: "Falar de roupas, sonhos e família",
    ref: "Gênesis 37:3-8", with: "juda",
    context: "Jacó deu a José uma túnica colorida. Na manhã seguinte, José conta um sonho aos irmãos.",
    vocab: [
      { en: "coat", pt: "túnica", icon: "🧥" }, { en: "colors", pt: "cores", icon: "🌈" },
      { en: "I had a dream", pt: "Eu tive um sonho", icon: "💭" }, { en: "last night", pt: "ontem à noite", icon: "🌙" }, { en: "brothers", pt: "irmãos", icon: "👨‍👦‍👦" },
    ],
    lines: [
      { who: "juda", en: "Joseph, is that a new coat?", pt: "José, essa túnica é nova?" },
      { who: "jose", en: "Yes! Father gave it to me. It has many colors.", pt: "Sim! Papai me deu. Ela tem muitas cores." },
      { who: "juda", en: "A coat of many colors... only for you?", pt: "Uma túnica de muitas cores... só para você?" },
      { who: "jose", en: "Brothers, listen. Last night I had a dream.", pt: "Irmãos, escutem. Ontem à noite eu tive um sonho." },
      { who: "juda", en: "Another dream? Tell us.", pt: "Outro sonho? Conte." },
      { who: "jose", en: "We were tying bundles of wheat. My bundle stood up, and yours bowed down to it.", pt: "Estávamos atando feixes de trigo. Meu feixe ficou em pé, e os de vocês se curvaram diante dele." },
      { who: "juda", en: "So you want to be our king? You want to rule over us?", pt: "Então você quer ser nosso rei? Quer mandar em nós?" },
      { who: "jose", en: "I only tell you what I dreamed.", pt: "Eu só conto o que sonhei." },
      { who: "juda", en: "We don't want to hear your dreams, Joseph.", pt: "Não queremos ouvir seus sonhos, José." },
    ],
    truth: "Israel amava José mais que aos outros filhos e fez para ele uma túnica de várias cores; os irmãos o odiavam; José contou o sonho dos feixes, e eles disseram \"reinarás tu sobre nós?\", odiando-o ainda mais (Gênesis 37:3-8).",
  },
  {
    id: "c-jose-2", char: "jose", unit: "u6", title: "Para onde vamos?", func: "Viajar: perguntar o destino, o tempo e a carga",
    ref: "Gênesis 37:25-28", with: "ismaelita",
    context: "Os irmãos vendem José por vinte moedas de prata a mercadores que vão para o Egito com camelos.",
    vocab: [
      { en: "Where are we going?", pt: "Para onde vamos?", icon: "🧭" }, { en: "trip", pt: "viagem", icon: "🧳" },
      { en: "How long does it take?", pt: "Quanto tempo leva?", icon: "⏱️" }, { en: "camel", pt: "camelo", icon: "🐪" }, { en: "to carry", pt: "levar, carregar", icon: "📦" },
    ],
    lines: [
      { who: "ismaelita", en: "Twenty pieces of silver. The boy is ours now. Get up.", pt: "Vinte moedas de prata. O menino agora é nosso. Levante-se." },
      { who: "jose", en: "Where are we going?", pt: "Para onde vamos?" },
      { who: "ismaelita", en: "To Egypt. It is a long trip.", pt: "Para o Egito. É uma viagem longa." },
      { who: "jose", en: "How long does it take?", pt: "Quanto tempo leva?" },
      { who: "ismaelita", en: "Many days. We travel by camel.", pt: "Muitos dias. Viajamos de camelo." },
      { who: "jose", en: "What are you carrying?", pt: "O que vocês estão levando?" },
      { who: "ismaelita", en: "Spices, balm and myrrh. We sell them in Egypt.", pt: "Especiarias, bálsamo e mirra. Vendemos no Egito." },
      { who: "jose", en: "Will I see my father again?", pt: "Vou ver meu pai de novo?" },
      { who: "ismaelita", en: "Don't talk. Walk. The sun is hot.", pt: "Não fale. Ande. O sol está quente." },
      { who: "jose", en: "I am afraid, but God is with me.", pt: "Estou com medo, mas Deus está comigo." },
    ],
    truth: "Passou uma caravana de ismaelitas vinda de Gileade, com camelos carregando especiarias, bálsamo e mirra para o Egito; Judá propôs vender José, e os irmãos o venderam por vinte moedas de prata; levaram-no ao Egito, e o Senhor estava com ele (Gênesis 37:25-28; 39:2).",
  },
  {
    id: "c-jose-3", char: "jose", unit: "u6", title: "Primeiro dia de trabalho", func: "No trabalho: dizer o que você sabe fazer",
    ref: "Gênesis 39:1-6", with: "potifar",
    context: "No Egito, José é comprado por Potifar, oficial do Faraó, e começa a trabalhar na casa dele.",
    vocab: [
      { en: "job", pt: "trabalho", icon: "💼" }, { en: "What can you do?", pt: "O que você sabe fazer?", icon: "🛠️" },
      { en: "to work hard", pt: "trabalhar duro", icon: "💪" }, { en: "in charge of", pt: "responsável por", icon: "🗝️" }, { en: "Yes, sir", pt: "Sim, senhor", icon: "✅" },
    ],
    lines: [
      { who: "potifar", en: "You are the new servant. What is your name?", pt: "Você é o servo novo. Qual é o seu nome?" },
      { who: "jose", en: "My name is Joseph. I come from Canaan.", pt: "Meu nome é José. Eu venho de Canaã." },
      { who: "potifar", en: "What can you do, Joseph?", pt: "O que você sabe fazer, José?" },
      { who: "jose", en: "I can take care of the house and the fields. I work hard, and I am honest.", pt: "Sei cuidar da casa e dos campos. Trabalho duro e sou honesto." },
      { who: "potifar", en: "Good. Start with the house. Work begins at sunrise.", pt: "Bom. Comece pela casa. O trabalho começa ao nascer do sol." },
      { who: "jose", en: "Yes, sir. I will do my best.", pt: "Sim, senhor. Farei o meu melhor." },
      { who: "potifar", en: "Joseph, everything you do goes well. Why?", pt: "José, tudo o que você faz dá certo. Por quê?" },
      { who: "jose", en: "Because the Lord is with me, sir.", pt: "Porque o Senhor está comigo, senhor." },
      { who: "potifar", en: "Then you are in charge of my whole house. Everything is in your hands.", pt: "Então você é responsável pela minha casa toda. Tudo está nas suas mãos." },
    ],
    truth: "Potifar, oficial de Faraó, comprou José; o Senhor estava com José, tudo o que ele fazia prosperava; Potifar viu isso e o pôs sobre a sua casa e sobre tudo o que tinha (Gênesis 39:1-6).",
  },
  {
    id: "c-jose-4", char: "jose", unit: "u6", title: "Por que essa cara triste?", func: "Perguntar como alguém está e falar dos próximos dias",
    ref: "Gênesis 40:1-23", with: "copeiro",
    context: "Na prisão, José cuida do copeiro e do padeiro do rei. Uma manhã, os dois acordam preocupados.",
    vocab: [
      { en: "Why do you look sad?", pt: "Por que você parece triste?", icon: "😟" }, { en: "to explain", pt: "explicar", icon: "💡" },
      { en: "in three days", pt: "em três dias", icon: "📅" }, { en: "to go back", pt: "voltar", icon: "↩️" }, { en: "Remember me", pt: "Lembre-se de mim", icon: "🧠" },
    ],
    lines: [
      { who: "jose", en: "Good morning. Why do you look so sad today?", pt: "Bom dia. Por que você está tão triste hoje?" },
      { who: "copeiro", en: "We both had a dream last night, and nobody can explain it.", pt: "Nós dois tivemos um sonho ontem à noite, e ninguém consegue explicar." },
      { who: "jose", en: "Explanations belong to God. Tell me your dream, please.", pt: "As explicações pertencem a Deus. Conte-me o seu sonho, por favor." },
      { who: "copeiro", en: "I saw a vine with three branches. I pressed the grapes into Pharaoh's cup.", pt: "Eu vi uma videira com três ramos. Espremi as uvas na taça do Faraó." },
      { who: "jose", en: "The three branches are three days. In three days you will go back to your job.", pt: "Os três ramos são três dias. Em três dias você vai voltar ao seu trabalho." },
      { who: "copeiro", en: "Back to the palace? In three days? Thank God!", pt: "De volta ao palácio? Em três dias? Graças a Deus!" },
      { who: "jose", en: "When things go well, remember me. Tell Pharaoh about me. I did nothing wrong.", pt: "Quando as coisas estiverem bem, lembre-se de mim. Fale de mim ao Faraó. Eu não fiz nada de errado." },
      { who: "copeiro", en: "I promise, Joseph. I will not forget you.", pt: "Prometo, José. Não vou esquecer você." },
    ],
    truth: "José perguntou ao copeiro e ao padeiro \"por que estão hoje tristes?\"; interpretou os sonhos (\"não são de Deus as interpretações?\"); em três dias o copeiro voltou ao cargo, o padeiro foi executado, e o copeiro esqueceu José por dois anos (Gênesis 40:6-23; 41:1).",
  },
  {
    id: "c-jose-5", char: "jose", unit: "u6", title: "Sete anos bons, sete anos ruins", func: "Fazer um plano com números e anos",
    ref: "Gênesis 41:14-41", with: "pharaoh",
    context: "Faraó teve um sonho que ninguém explica. O copeiro finalmente lembra de José, que é tirado da prisão.",
    vocab: [
      { en: "seven years", pt: "sete anos", icon: "7️⃣" }, { en: "fat / thin", pt: "gordo / magro", icon: "🐄" },
      { en: "plan", pt: "plano", icon: "🗒️" }, { en: "to save (food)", pt: "guardar, poupar", icon: "🏦" }, { en: "one fifth", pt: "um quinto", icon: "🍰" },
    ],
    lines: [
      { who: "pharaoh", en: "I had a dream and no one can explain it. They say you can.", pt: "Eu tive um sonho e ninguém consegue explicar. Dizem que você consegue." },
      { who: "jose", en: "Not me, but God will give Pharaoh a good answer.", pt: "Eu não, mas Deus dará ao Faraó uma boa resposta." },
      { who: "pharaoh", en: "Seven fat cows came out of the river. Then seven thin cows ate them.", pt: "Sete vacas gordas saíram do rio. Depois sete vacas magras as comeram." },
      { who: "jose", en: "The seven fat cows are seven good years. The seven thin cows are seven years of famine.", pt: "As sete vacas gordas são sete anos bons. As sete vacas magras são sete anos de fome." },
      { who: "pharaoh", en: "Seven years of famine? What can we do?", pt: "Sete anos de fome? O que podemos fazer?" },
      { who: "jose", en: "Choose a wise man. In the good years, save one fifth of the food.", pt: "Escolha um homem sábio. Nos anos bons, guarde um quinto da comida." },
      { who: "pharaoh", en: "Save one fifth every year, for seven years...", pt: "Guardar um quinto por ano, durante sete anos..." },
      { who: "jose", en: "Yes. Keep the grain in the cities. Then there will be food in the bad years.", pt: "Sim. Guarde o grão nas cidades. Assim haverá comida nos anos ruins." },
      { who: "pharaoh", en: "God's Spirit is in you. You will be in charge of all Egypt.", pt: "O Espírito de Deus está em você. Você será responsável por todo o Egito." },
    ],
    truth: "José explicou: sete vacas gordas e sete espigas boas são sete anos de fartura, as magras são sete anos de fome; aconselhou guardar a quinta parte nos anos bons; Faraó o pôs sobre toda a terra do Egito (Gênesis 41:25-41).",
  },
  {
    id: "c-jose-6", char: "jose", unit: "u6", title: "Eu sou José", func: "Reencontrar a família, perdoar e convidar para morar perto",
    ref: "Gênesis 45:1-11", with: "juda",
    context: "Anos depois, os irmãos vêm comprar comida no Egito sem saber quem é o governador. José não aguenta mais.",
    vocab: [
      { en: "Come near", pt: "Chegue perto", icon: "🤗" }, { en: "still alive", pt: "ainda vivo", icon: "❤️" },
      { en: "Don't be sad", pt: "Não fique triste", icon: "🙂" }, { en: "Hurry!", pt: "Depressa!", icon: "🏃" }, { en: "to take care of", pt: "cuidar de", icon: "🛡️" },
    ],
    lines: [
      { who: "jose", en: "Come near, please. I am Joseph. Is my father still alive?", pt: "Cheguem perto, por favor. Eu sou José. Meu pai ainda está vivo?" },
      { who: "juda", en: "Joseph?! It can't be... We are so afraid.", pt: "José?! Não pode ser... Estamos com tanto medo." },
      { who: "jose", en: "Don't be sad, and don't be angry with yourselves.", pt: "Não fiquem tristes, nem com raiva de si mesmos." },
      { who: "juda", en: "But we sold you. We were wrong.", pt: "Mas nós vendemos você. Nós erramos." },
      { who: "jose", en: "God sent me here before you, to save lives. There are still five years of famine.", pt: "Deus me enviou aqui antes de vocês, para salvar vidas. Ainda faltam cinco anos de fome." },
      { who: "juda", en: "Five more years? What can we do?", pt: "Mais cinco anos? O que podemos fazer?" },
      { who: "jose", en: "Hurry! Go to my father and bring him here. You will live in Goshen, near me.", pt: "Depressa! Vão ao meu pai e o tragam aqui. Vocês vão morar em Gósen, perto de mim." },
      { who: "juda", en: "All of us? Our children, our sheep, everything?", pt: "Todos nós? Nossos filhos, nossas ovelhas, tudo?" },
      { who: "jose", en: "Yes, all of you. I will take care of you.", pt: "Sim, todos vocês. Eu vou cuidar de vocês." },
    ],
    truth: "José se deu a conhecer: \"eu sou José; vive ainda meu pai?\"; \"chegai-vos a mim\"; \"não vos entristeçais... Deus me enviou adiante de vós para conservar a vida\"; ainda faltavam cinco anos de fome; mandou trazer Jacó para morar em Gósen e prometeu sustentá-los (Gênesis 45:1-11).",
  },

  // ===================== DANIEL (capítulo 7) =====================
  {
    id: "c-daniel-1", char: "daniel", unit: "u7", title: "Legumes e água, por dez dias", func: "Pedir uma comida diferente e combinar um teste",
    ref: "Daniel 1:8-16", with: "mordomo",
    context: "Na Babilônia, Daniel e seus amigos recebem a comida da mesa do rei. Daniel decide não se contaminar.",
    vocab: [
      { en: "dinner", pt: "jantar", icon: "🍽️" }, { en: "vegetables", pt: "legumes", icon: "🥦" },
      { en: "I can't eat this", pt: "Não posso comer isto", icon: "🙅" }, { en: "ten days", pt: "dez dias", icon: "🔟" }, { en: "stronger", pt: "mais forte", icon: "💪" },
    ],
    lines: [
      { who: "mordomo", en: "Here is your dinner: meat and wine from the king's table.", pt: "Aqui está o seu jantar: carne e vinho da mesa do rei." },
      { who: "daniel", en: "Thank you, but I cannot eat this food.", pt: "Obrigado, mas eu não posso comer esta comida." },
      { who: "mordomo", en: "Why not? It is the best food in Babylon.", pt: "Por que não? É a melhor comida da Babilônia." },
      { who: "daniel", en: "It is against my faith. Please give us vegetables and water.", pt: "É contra a minha fé. Por favor, nos dê legumes e água." },
      { who: "mordomo", en: "Only vegetables? You will look thin, and the king will cut off my head.", pt: "Só legumes? Vocês vão ficar magros, e o rei vai cortar a minha cabeça." },
      { who: "daniel", en: "Test us for ten days. Then look at our faces.", pt: "Teste-nos por dez dias. Depois olhe para os nossos rostos." },
      { who: "mordomo", en: "Ten days. Vegetables and water. Fine.", pt: "Dez dias. Legumes e água. Está bem." },
      { who: "daniel", en: "So? After ten days, how do we look?", pt: "E então? Depois de dez dias, como estamos?" },
      { who: "mordomo", en: "Better and stronger than all the others! Vegetables for everyone, then.", pt: "Melhores e mais fortes que todos os outros! Legumes para todos, então." },
    ],
    truth: "Daniel resolveu não se contaminar com a comida do rei; pediu ao cozinheiro-chefe: \"experimenta os teus servos dez dias, com legumes e água\"; ao fim dos dez dias estavam melhores e mais nutridos que os outros jovens (Daniel 1:8-16).",
  },
  {
    id: "c-daniel-2", char: "daniel", unit: "u7", title: "Uma língua nova, um nome novo", func: "Na escola: aprender uma língua e apresentar-se com um nome novo",
    ref: "Daniel 1:3-7, 17-20", with: "aspenaz",
    context: "Aspenaz, chefe dos oficiais, recebe os jovens de Judá na escola do palácio. Eles vão estudar por três anos.",
    vocab: [
      { en: "school", pt: "escola", icon: "🏫" }, { en: "to learn", pt: "aprender", icon: "📚" },
      { en: "language", pt: "língua, idioma", icon: "🗣️" }, { en: "three years", pt: "três anos", icon: "3️⃣" }, { en: "Don't be late", pt: "Não se atrase", icon: "⏰" },
    ],
    lines: [
      { who: "aspenaz", en: "Welcome to the king's school. What is your name?", pt: "Bem-vindo à escola do rei. Qual é o seu nome?" },
      { who: "daniel", en: "My name is Daniel. I am from Jerusalem.", pt: "Meu nome é Daniel. Eu sou de Jerusalém." },
      { who: "aspenaz", en: "Here your new name is Belteshazzar. You will study for three years.", pt: "Aqui o seu novo nome é Beltessazar. Você vai estudar por três anos." },
      { who: "daniel", en: "Three years? What will we learn?", pt: "Três anos? O que vamos aprender?" },
      { who: "aspenaz", en: "The language and the books of the Chaldeans. It is difficult.", pt: "A língua e os livros dos caldeus. É difícil." },
      { who: "daniel", en: "I like to learn. I will practice every day.", pt: "Eu gosto de aprender. Vou praticar todos os dias." },
      { who: "aspenaz", en: "Your friends have new names too: Shadrach, Meshach and Abednego.", pt: "Seus amigos também têm nomes novos: Sadraque, Mesaque e Abede-Nego." },
      { who: "daniel", en: "New names, new language, but the same God.", pt: "Nomes novos, língua nova, mas o mesmo Deus." },
      { who: "aspenaz", en: "Class starts tomorrow morning. Don't be late.", pt: "A aula começa amanhã de manhã. Não se atrase." },
    ],
    truth: "Aspenaz recebeu jovens de Judá para aprender as letras e a língua dos caldeus por três anos; deu-lhes nomes novos (Daniel: Beltessazar); Deus lhes deu conhecimento, e o rei os achou dez vezes melhores que todos os sábios (Daniel 1:3-7, 17-20).",
  },
  {
    id: "c-daniel-3", char: "daniel", unit: "u7", title: "Dê-me um pouco de tempo", func: "Pedir mais tempo e marcar um horário",
    ref: "Daniel 2:1-47", with: "nabucodonosor",
    context: "O rei Nabucodonosor teve um sonho e exige que os sábios contem o sonho e o sentido. Ninguém consegue.",
    vocab: [
      { en: "Give me time", pt: "Dê-me tempo", icon: "⏳" }, { en: "tomorrow", pt: "amanhã", icon: "📆" },
      { en: "tonight", pt: "hoje à noite", icon: "🌙" }, { en: "worried", pt: "preocupado", icon: "😟" }, { en: "secret", pt: "segredo", icon: "🤫" },
    ],
    lines: [
      { who: "nabucodonosor", en: "I had a dream and I am worried. Tell me the dream and its meaning!", pt: "Tive um sonho e estou preocupado. Diga-me o sonho e o seu sentido!" },
      { who: "daniel", en: "Give me some time, my king. Tomorrow I will bring the answer.", pt: "Dê-me um pouco de tempo, meu rei. Amanhã eu trago a resposta." },
      { who: "nabucodonosor", en: "Tomorrow? The wise men could not do it in many days.", pt: "Amanhã? Os sábios não conseguiram em muitos dias." },
      { who: "daniel", en: "Tonight I will pray with my friends. God knows every secret.", pt: "Hoje à noite vou orar com meus amigos. Deus conhece todos os segredos." },
      { who: "nabucodonosor", en: "Well, Daniel? It is morning. Can you tell me my dream?", pt: "E então, Daniel? Já é de manhã. Pode me dizer o meu sonho?" },
      { who: "daniel", en: "No wise man can. But there is a God in heaven who reveals secrets.", pt: "Nenhum sábio consegue. Mas há um Deus no céu que revela segredos." },
      { who: "nabucodonosor", en: "Speak.", pt: "Fale." },
      { who: "daniel", en: "You saw a big statue. Its head was gold, the chest silver, the belly bronze, the legs iron.", pt: "O senhor viu uma grande estátua. A cabeça era de ouro, o peito de prata, o ventre de bronze, as pernas de ferro." },
      { who: "nabucodonosor", en: "That is my dream! Your God is the God of gods.", pt: "É o meu sonho! O seu Deus é o Deus dos deuses." },
    ],
    truth: "Daniel pediu ao rei que lhe desse tempo; orou com Hananias, Misael e Azarias; o segredo foi revelado numa visão de noite; ele descreveu a estátua de ouro, prata, bronze, ferro e barro, e o rei disse \"o vosso Deus é o Deus dos deuses\" (Daniel 2:16-19, 31-47).",
  },
  {
    id: "c-daniel-4", char: "daniel", unit: "u7", title: "A escrita na parede", func: "Pedir para alguém ler e explicar uma mensagem",
    ref: "Daniel 5:1-30", with: "belsazar",
    context: "No banquete do rei Belsazar, uma mão escreve na parede. Ninguém sabe ler. Chamam Daniel.",
    vocab: [
      { en: "to read", pt: "ler", icon: "📖" }, { en: "wall", pt: "parede", icon: "🧱" },
      { en: "What does it mean?", pt: "O que significa?", icon: "❓" }, { en: "gift", pt: "presente", icon: "🎁" }, { en: "to count", pt: "contar", icon: "🔢" },
    ],
    lines: [
      { who: "belsazar", en: "Are you Daniel? A hand wrote on the wall and nobody can read it.", pt: "Você é Daniel? Uma mão escreveu na parede e ninguém consegue ler." },
      { who: "daniel", en: "I see the words, my king.", pt: "Eu vejo as palavras, meu rei." },
      { who: "belsazar", en: "Read it for me and I will give you gold and a purple robe.", pt: "Leia para mim e eu lhe dou ouro e um manto púrpura." },
      { who: "daniel", en: "Keep your gifts. But I will read it and explain it.", pt: "Fique com os seus presentes. Mas eu vou ler e explicar." },
      { who: "belsazar", en: "What does it say?", pt: "O que está escrito?" },
      { who: "daniel", en: "Mene, mene, tekel, parsin.", pt: "Mene, mene, tequel, parsim." },
      { who: "belsazar", en: "What does it mean?", pt: "O que significa?" },
      { who: "daniel", en: "Mene: God counted the days of your kingdom. Tekel: you were weighed and found light. Parsin: your kingdom is divided.", pt: "Mene: Deus contou os dias do seu reino. Tequel: o senhor foi pesado e achado leve. Parsim: o seu reino está dividido." },
      { who: "belsazar", en: "Bring the purple robe and the gold chain. He is now third in the kingdom.", pt: "Tragam o manto púrpura e a corrente de ouro. Ele agora é o terceiro no reino." },
    ],
    truth: "Belsazar deu um banquete e bebeu nos vasos do templo; dedos de mão escreveram na parede; Daniel recusou os presentes, leu \"MENE, MENE, TEQUEL e PARSIM\" e explicou; mesmo assim foi vestido de púrpura e feito terceiro no reino; naquela noite Belsazar foi morto (Daniel 5:1-30).",
  },
  {
    id: "c-daniel-5", char: "daniel", unit: "u7", title: "Três vezes por dia", func: "Falar da rotina e das horas do dia",
    ref: "Daniel 6:4-11", with: "oficial",
    context: "Os oficiais invejosos convencem o rei Dario a proibir orações por trinta dias. Um deles vai sondar Daniel.",
    vocab: [
      { en: "every day", pt: "todos os dias", icon: "📆" }, { en: "in the morning", pt: "de manhã", icon: "🌅" },
      { en: "at noon", pt: "ao meio-dia", icon: "☀️" }, { en: "in the evening", pt: "à noite", icon: "🌇" }, { en: "window", pt: "janela", icon: "🪟" },
    ],
    lines: [
      { who: "oficial", en: "Daniel, what do you do every day?", pt: "Daniel, o que você faz todos os dias?" },
      { who: "daniel", en: "I work for the king. And three times a day, I pray.", pt: "Eu trabalho para o rei. E três vezes por dia, eu oro." },
      { who: "oficial", en: "Three times? When?", pt: "Três vezes? Quando?" },
      { who: "daniel", en: "In the morning, at noon and in the evening. I open my window toward Jerusalem.", pt: "De manhã, ao meio-dia e à noite. Eu abro a minha janela na direção de Jerusalém." },
      { who: "oficial", en: "Did you hear about the new law? For thirty days, no one can pray to any god, only to the king.", pt: "Você soube da nova lei? Por trinta dias, ninguém pode orar a nenhum deus, só ao rei." },
      { who: "daniel", en: "I heard. But I pray to my God every day, as always.", pt: "Eu soube. Mas eu oro ao meu Deus todos os dias, como sempre." },
      { who: "oficial", en: "The punishment is the lions' den!", pt: "O castigo é a cova dos leões!" },
      { who: "daniel", en: "I know. Now excuse me, it is time to pray.", pt: "Eu sei. Agora com licença, é hora de orar." },
    ],
    truth: "Os príncipes fizeram o rei assinar um decreto: por trinta dias, petições só ao rei, sob pena da cova dos leões; Daniel, sabendo disso, foi para casa, abriu as janelas na direção de Jerusalém e orou três vezes ao dia, como antes (Daniel 6:6-11).",
  },
  {
    id: "c-daniel-6", char: "daniel", unit: "u7", title: "Bom dia, meu rei", func: "Cumprimentar de manhã e perguntar se alguém está bem",
    ref: "Daniel 6:16-27", with: "dario",
    context: "Daniel passou a noite na cova dos leões. Ao amanhecer, o rei Dario corre até a cova, aflito.",
    vocab: [
      { en: "Good morning", pt: "Bom dia", icon: "🌅" }, { en: "Are you alive?", pt: "Você está vivo?", icon: "❤️" },
      { en: "Are you hurt?", pt: "Você está machucado?", icon: "🩹" }, { en: "night", pt: "noite", icon: "🌙" }, { en: "lion", pt: "leão", icon: "🦁" },
    ],
    lines: [
      { who: "dario", en: "Daniel! Servant of the living God! Are you alive? Did your God save you from the lions?", pt: "Daniel! Servo do Deus vivo! Você está vivo? O seu Deus o salvou dos leões?" },
      { who: "daniel", en: "Good morning, my king. May you live forever!", pt: "Bom dia, meu rei. Que o senhor viva para sempre!" },
      { who: "dario", en: "You are alive! How did you spend the night with the lions?", pt: "Você está vivo! Como passou a noite com os leões?" },
      { who: "daniel", en: "God sent his angel. He shut the lions' mouths.", pt: "Deus enviou o seu anjo. Ele fechou a boca dos leões." },
      { who: "dario", en: "Are you hurt?", pt: "Você está machucado?" },
      { who: "daniel", en: "No, not at all. I did nothing wrong before God or before you, my king.", pt: "Não, nem um pouco. Eu não fiz nada de errado diante de Deus nem diante do senhor, meu rei." },
      { who: "dario", en: "Take him out of the den, quickly!", pt: "Tirem-no da cova, depressa!" },
      { who: "daniel", en: "Thank you, my king. It was a long night, but God was with me.", pt: "Obrigado, meu rei. Foi uma noite longa, mas Deus estava comigo." },
      { who: "dario", en: "Today I write a new law: everyone must respect the God of Daniel.", pt: "Hoje eu escrevo uma nova lei: todos devem respeitar o Deus de Daniel." },
    ],
    truth: "O rei passou a noite em jejum e, de madrugada, correu à cova: \"Daniel, servo do Deus vivo, o teu Deus pôde livrar-te dos leões?\"; Daniel: \"ó rei, vive para sempre! O meu Deus enviou o seu anjo e fechou a boca dos leões\"; nenhum dano foi achado nele, e Dario decretou que todos tremessem diante do Deus de Daniel (Daniel 6:19-27).",
  },

  // ===================== PEDRO (capítulo 8) =====================
  {
    id: "c-pedro-1", char: "pedro", unit: "u8", title: "Trabalhamos a noite toda", func: "Falar do trabalho: uma noite difícil e um resultado inesperado",
    ref: "Lucas 5:1-11", with: "jesus",
    context: "De manhã, no lago de Genesaré, Pedro lava as redes depois de uma noite sem pescar nada. Jesus entra no barco dele.",
    vocab: [
      { en: "all night", pt: "a noite toda", icon: "🌙" }, { en: "nothing", pt: "nada", icon: "🚫" },
      { en: "Try again", pt: "Tente de novo", icon: "🔁" }, { en: "so many", pt: "tantos", icon: "🐟" }, { en: "to help", pt: "ajudar", icon: "🤝" },
    ],
    lines: [
      { who: "jesus", en: "Simon, take the boat into deep water and let down the nets.", pt: "Simão, leve o barco para a água funda e lance as redes." },
      { who: "pedro", en: "Master, we worked all night and caught nothing.", pt: "Mestre, trabalhamos a noite toda e não pegamos nada." },
      { who: "jesus", en: "Try again, now.", pt: "Tente de novo, agora." },
      { who: "pedro", en: "Because you say so, I will let down the net.", pt: "Porque o senhor diz, eu vou lançar a rede." },
      { who: "jesus", en: "Look at the net.", pt: "Olhe a rede." },
      { who: "pedro", en: "So many fish! The net is breaking! James, John, come and help us!", pt: "Tantos peixes! A rede está rasgando! Tiago, João, venham nos ajudar!" },
      { who: "jesus", en: "Two boats are full now.", pt: "Os dois barcos estão cheios agora." },
      { who: "pedro", en: "Lord, go away from me. I am a sinful man.", pt: "Senhor, afaste-se de mim. Eu sou um homem pecador." },
      { who: "jesus", en: "Don't be afraid. From now on you will catch people.", pt: "Não tenha medo. De agora em diante você vai pescar pessoas." },
    ],
    truth: "Jesus entrou no barco de Simão, mandou lançar as redes; Simão disse \"trabalhamos toda a noite e nada apanhamos, mas sobre a tua palavra lançarei a rede\"; a rede rompia, encheram dois barcos, Pedro caiu aos pés de Jesus, e Jesus disse \"de agora em diante serás pescador de homens\" (Lucas 5:4-11).",
  },
  {
    id: "c-pedro-2", char: "pedro", unit: "u8", title: "Senhor, salva-me!", func: "Pedir socorro numa emergência",
    ref: "Mateus 14:24-33", with: "jesus",
    context: "De madrugada, o barco luta contra o vento no meio do mar. Os discípulos veem alguém andando sobre a água.",
    vocab: [
      { en: "Help!", pt: "Socorro!", icon: "🆘" }, { en: "wind", pt: "vento", icon: "🌬️" },
      { en: "to sink", pt: "afundar", icon: "🌊" }, { en: "Save me!", pt: "Salva-me!", icon: "🙏" }, { en: "Take courage", pt: "Tenha coragem", icon: "💪" },
    ],
    lines: [
      { who: "pedro", en: "Look! Someone is walking on the water! Is it a ghost?", pt: "Olhem! Alguém está andando sobre a água! É um fantasma?" },
      { who: "jesus", en: "Take courage! It is I. Don't be afraid.", pt: "Tenham coragem! Sou eu. Não tenham medo." },
      { who: "pedro", en: "Lord, if it is you, tell me to come to you on the water.", pt: "Senhor, se é o senhor, mande-me ir até aí sobre a água." },
      { who: "jesus", en: "Come.", pt: "Venha." },
      { who: "pedro", en: "I am walking on the water! But the wind is so strong... I am sinking! Lord, save me!", pt: "Estou andando sobre a água! Mas o vento é tão forte... Estou afundando! Senhor, salva-me!" },
      { who: "jesus", en: "I've got you. Why did you doubt? You have little faith.", pt: "Eu seguro você. Por que duvidou? Você tem pouca fé." },
      { who: "pedro", en: "I looked at the waves, not at you.", pt: "Eu olhei para as ondas, não para o senhor." },
      { who: "jesus", en: "Let's get into the boat.", pt: "Vamos entrar no barco." },
      { who: "pedro", en: "The wind stopped. Truly you are the Son of God.", pt: "O vento parou. Verdadeiramente o senhor é o Filho de Deus." },
    ],
    truth: "Na quarta vigília da noite Jesus foi andando sobre o mar; os discípulos gritaram \"é um fantasma\"; Pedro pediu \"manda-me ir ter contigo\", andou sobre as águas, temeu o vento, começou a afundar e gritou \"Senhor, salva-me!\"; Jesus o segurou, o vento cessou (Mateus 14:25-33).",
  },
  {
    id: "c-pedro-3", char: "pedro", unit: "u8", title: "Quem dizem que eu sou?", func: "Falar sobre pessoas: quem é quem e o que dizem",
    ref: "Mateus 16:13-18", with: "jesus",
    context: "Na região de Cesareia de Filipe, andando pela estrada, Jesus faz uma pergunta aos discípulos.",
    vocab: [
      { en: "Who?", pt: "Quem?", icon: "❓" }, { en: "people say", pt: "as pessoas dizem", icon: "🗣️" },
      { en: "others", pt: "outros", icon: "👥" }, { en: "And you?", pt: "E você?", icon: "👉" }, { en: "rock", pt: "pedra", icon: "🪨" },
    ],
    lines: [
      { who: "jesus", en: "Who do people say that I am?", pt: "Quem as pessoas dizem que eu sou?" },
      { who: "pedro", en: "Some say John the Baptist. Others say Elijah or Jeremiah.", pt: "Alguns dizem João Batista. Outros dizem Elias ou Jeremias." },
      { who: "jesus", en: "And you? Who do you say that I am?", pt: "E vocês? Quem vocês dizem que eu sou?" },
      { who: "pedro", en: "You are the Christ, the Son of the living God.", pt: "O senhor é o Cristo, o Filho do Deus vivo." },
      { who: "jesus", en: "Blessed are you, Simon. My Father in heaven showed you this.", pt: "Bem-aventurado é você, Simão. Meu Pai no céu lhe mostrou isso." },
      { who: "pedro", en: "Your Father showed me?", pt: "Seu Pai me mostrou?" },
      { who: "jesus", en: "Yes. And I say to you: you are Peter, and on this rock I will build my church.", pt: "Sim. E eu lhe digo: você é Pedro, e sobre esta pedra edificarei a minha igreja." },
      { who: "pedro", en: "Peter... the rock. Thank you, Lord.", pt: "Pedro... a pedra. Obrigado, Senhor." },
    ],
    truth: "Em Cesareia de Filipe Jesus perguntou \"quem dizem os homens ser o Filho do homem?\"; responderam João Batista, Elias, Jeremias; \"e vós?\"; Pedro: \"tu és o Cristo, o Filho do Deus vivo\"; Jesus: \"bem-aventurado és tu, Simão... tu és Pedro, e sobre esta pedra edificarei a minha igreja\" (Mateus 16:13-18).",
  },
  {
    id: "c-pedro-4", char: "pedro", unit: "u8", title: "Eu não conheço esse homem", func: "Dizer que não conhece alguém (e o peso de um não)",
    ref: "Lucas 22:54-62", with: "serva",
    context: "Jesus foi preso. No pátio do sumo sacerdote, Pedro se aquece junto ao fogo. Uma serva olha bem para ele.",
    vocab: [
      { en: "I don't know him", pt: "Eu não o conheço", icon: "🤷" }, { en: "fire", pt: "fogo", icon: "🔥" },
      { en: "rooster", pt: "galo", icon: "🐓" }, { en: "three times", pt: "três vezes", icon: "3️⃣" }, { en: "to cry", pt: "chorar", icon: "😭" },
    ],
    lines: [
      { who: "serva", en: "Wait. I know you. You were with that man, Jesus.", pt: "Espere. Eu conheço você. Você estava com aquele homem, Jesus." },
      { who: "pedro", en: "Woman, I don't know him.", pt: "Mulher, eu não o conheço." },
      { who: "serva", en: "Yes, you were! You are one of his friends.", pt: "Estava, sim! Você é um dos amigos dele." },
      { who: "pedro", en: "I am not! I don't know what you are talking about.", pt: "Não sou! Não sei do que você está falando." },
      { who: "serva", en: "You talk like a Galilean. You are one of them.", pt: "Você fala como galileu. Você é um deles." },
      { who: "pedro", en: "I told you, I don't know the man!", pt: "Eu já disse, eu não conheço esse homem!" },
      { who: "serva", en: "Listen... the rooster is crowing.", pt: "Escute... o galo está cantando." },
      { who: "pedro", en: "The rooster... Jesus said: before the rooster crows, you will deny me three times.", pt: "O galo... Jesus disse: antes que o galo cante, você me negará três vezes." },
    ],
    truth: "Pedro seguiu de longe e sentou-se junto ao fogo no pátio; uma criada disse \"este também estava com ele\", e ele negou; negou mais duas vezes; o galo cantou, o Senhor se virou e olhou para Pedro, e ele saiu e chorou amargamente (Lucas 22:54-62). Depois da ressurreição, Jesus o restaurou (João 21:15-17).",
  },
  {
    id: "c-pedro-5", char: "pedro", unit: "u8", title: "Café da manhã na praia", func: "Convidar para comer e falar de amor",
    ref: "João 21:1-17", with: "jesus",
    context: "Depois da ressurreição, Pedro volta a pescar. De manhã, alguém na praia chama os discípulos.",
    vocab: [
      { en: "breakfast", pt: "café da manhã", icon: "🍳" }, { en: "right side", pt: "lado direito", icon: "👉" },
      { en: "bread", pt: "pão", icon: "🍞" }, { en: "Do you love me?", pt: "Você me ama?", icon: "❤️" }, { en: "to feed", pt: "alimentar, apascentar", icon: "🐑" },
    ],
    lines: [
      { who: "jesus", en: "Friends, do you have any fish?", pt: "Amigos, vocês têm algum peixe?" },
      { who: "pedro", en: "No. Nothing all night.", pt: "Não. Nada a noite toda." },
      { who: "jesus", en: "Throw the net on the right side of the boat.", pt: "Lancem a rede do lado direito do barco." },
      { who: "pedro", en: "The net is full! John says it is the Lord. I am jumping into the water!", pt: "A rede está cheia! João diz que é o Senhor. Vou pular na água!" },
      { who: "jesus", en: "Come and have breakfast. The fish are on the fire, and there is bread.", pt: "Venham tomar café da manhã. Os peixes estão no fogo, e há pão." },
      { who: "pedro", en: "One hundred and fifty-three fish! And the net is not broken.", pt: "Cento e cinquenta e três peixes! E a rede não rasgou." },
      { who: "jesus", en: "Simon, son of Jonas, do you love me?", pt: "Simão, filho de Jonas, você me ama?" },
      { who: "pedro", en: "Yes, Lord. You know that I love you.", pt: "Sim, Senhor. O senhor sabe que eu o amo." },
      { who: "jesus", en: "Then feed my sheep.", pt: "Então apascente as minhas ovelhas." },
    ],
    truth: "Jesus, na praia, perguntou \"filhos, tendes alguma coisa de comer?\"; mandou lançar a rede à direita; João disse \"é o Senhor\" e Pedro se lançou ao mar; havia brasas com peixe e pão; foram 153 peixes e a rede não se rompeu; três vezes Jesus perguntou \"Simão, filho de Jonas, amas-me?\" e disse \"apascenta as minhas ovelhas\" (João 21:5-17).",
  },
  {
    id: "c-pedro-6", char: "pedro", unit: "u8", title: "Não tenho prata nem ouro", func: "Falar de dinheiro e oferecer o que se tem",
    ref: "Atos 3:1-8", with: "coxo",
    context: "Às três da tarde, hora da oração, Pedro e João sobem ao templo. Na porta Formosa, um homem coxo pede esmola.",
    vocab: [
      { en: "money", pt: "dinheiro", icon: "💰" }, { en: "coin", pt: "moeda", icon: "🪙" },
      { en: "I have no...", pt: "Eu não tenho...", icon: "🚫" }, { en: "silver and gold", pt: "prata e ouro", icon: "✨" }, { en: "Get up and walk", pt: "Levante-se e ande", icon: "🚶" },
    ],
    lines: [
      { who: "coxo", en: "Sir, a coin, please. Just one coin.", pt: "Senhor, uma moeda, por favor. Só uma moeda." },
      { who: "pedro", en: "Look at us.", pt: "Olhe para nós." },
      { who: "coxo", en: "I am looking. Do you have something for me?", pt: "Estou olhando. O senhor tem alguma coisa para mim?" },
      { who: "pedro", en: "I have no silver and no gold.", pt: "Eu não tenho prata nem ouro." },
      { who: "coxo", en: "No money at all?", pt: "Nenhum dinheiro?" },
      { who: "pedro", en: "But what I have, I give you: in the name of Jesus Christ of Nazareth, get up and walk!", pt: "Mas o que eu tenho, eu lhe dou: em nome de Jesus Cristo de Nazaré, levante-se e ande!" },
      { who: "coxo", en: "My feet... my legs are strong! I can walk! I can jump!", pt: "Meus pés... minhas pernas estão fortes! Eu consigo andar! Consigo pular!" },
      { who: "pedro", en: "Come with us to the temple. It is three o'clock, time to pray.", pt: "Venha conosco ao templo. São três horas, hora de orar." },
      { who: "coxo", en: "Praise God! Praise God!", pt: "Louvado seja Deus! Louvado seja Deus!" },
    ],
    truth: "Pedro e João subiram ao templo à hora nona (três da tarde); um coxo de nascença pedia esmola na porta Formosa; Pedro disse \"olha para nós... não tenho prata nem ouro, mas o que tenho isso te dou: em nome de Jesus Cristo, o Nazareno, levanta-te e anda\"; ele saltou, andou e entrou no templo louvando a Deus (Atos 3:1-8).",
  }
);
